<div class="alert alert-block alert-info">
<b>TBA:</b> jcash will improve text here

    I need to finish up the arrangement of the sections and then set the section numbers

    I need to create the assignments
</div>

<div class="alert alert-block alert-warning">
<b>Caution:</b> Use this when a section is unclear
</div>

# Tutorial More on NumPy 

<div class="alert alert-block alert-info">
<b>TBA:</b> jcash will improve text here
</div>

## Overview

### Imports needed

In [3]:
import numpy as np

## Review of NumPy

### NumPy math operations

### NumPy Arrays

### Numpy as a package import


In [5]:
angle_deg = 60
angle_rad = np.deg2rad(angle_deg)
print("an angle of ", angle_deg," degrees is equal to ", angle_rad," radians")

an angle of  60  degrees is equal to  1.0471975511965976  radians


In [7]:
angle_rad = 1.3
angle_deg = np.rad2deg(angle_rad)
print("an angle of ", angle_rad," radians is equal to ", angle_deg," degrees")

an angle of  1.3  radians is equal to  74.48451336700703  degrees


In [13]:
import numpy as np

In [15]:
#Defining both the matrices.
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

In [17]:
#Performing addition using arithmetic operator.
add_ans = a+b
print(add_ans)

[  7  77  23 130]


In [19]:
#Performing addition using numpy function.
add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]


In [21]:
#This would work.
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

[  8  79  26 134]


In [23]:
#But here NumPy only considers the first two arrays (a and b) and ignores the third one (c).
add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]


In [25]:
#Defining both the matrices.
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

In [27]:
#Performing subtraction using arithmetic operator.
sub_ans = a-b
print(sub_ans)

[ 3 67  3 70]


In [29]:
#Performing subtraction using numpy function.
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]


In [31]:
#Defining both the matrices.
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

In [33]:
#Performing subtraction using arithmetic operator.
sub_ans = a-b-1
print(sub_ans)

[ 2 66  2 69]


In [35]:
#Performing subtraction using numpy function.
sub_ans = np.subtract(a, b)-1
print(sub_ans)

[ 2 66  2 69]


In [37]:
#Performing multiplication using arithmetic operator.
mul_ans = a*b
print(mul_ans)

[  10  360  130 3000]


In [33]:
#Performing multiplication using numpy function.
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


In [39]:
#Performing division using arithmetic operators.
div_ans = a/b
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [41]:
#Performing division using numpy functions.
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [43]:
#Performing mod on two matrices.
mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


In [45]:
#Performing remainder on two matrices.
rem_ans=np.remainder(a,b)
print(rem_ans)

[ 1  2  3 10]


In [47]:
#Performing power of two matrices.
pow_ans = np.power(a, b)
print(pow_ans)

[        25 1934917632  419538377          0]


In [51]:
#Getting mean of all numbers in 'a'.
mean_a = np.mean(a)
print(mean_a)

47.5


In [53]:
#Getting average of all numbers in 'b'.
mean_b = np.average(b)
print(mean_b)

11.75


In [55]:
#Getting sum of all numbers in 'a'.
sum_a = np.sum(a)
print(sum_a)

190


In [57]:
#Getting variance of all number in 'b'.
var_b = np.var(b)
print(var_b)

119.1875


In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Creating NumPy arrays

Manually added was in tutorial 3.

In [61]:
#0D arrays.
import numpy as np

arr = np.array(42)

print(arr)

42


In [63]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [65]:
#1D arrays.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [67]:
#2D arrays.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [69]:
#3D arrays.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [71]:
#Checking number of dimensions.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [68]:
#Higher dimensional arrays.
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Empty array

### Zero arrays and ones

<div class="alert alert-block alert-warning">
<b>Caution:</b> Use this when a section is unclear
</div>

In [75]:
#Creating an array of zeros.
zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("\nZeros Array:")
print(zeros_array)


Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [77]:
#Creating an array of ones.
ones_array = np.ones((3, 2))  # 3 rows, 2 columns
print("\nOnes Array:")
print(ones_array)


Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [79]:
#Ranged arrays
range_array = np.arange(20)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [81]:
#Random arrays.

#Creating an array with random values.
random_array = np.random.rand(2, 3)  # 2 rows, 3 columns
print("\nRandom Array:")
print(random_array)


Random Array:
[[0.68219786 0.5981278  0.08797941]
 [0.11969875 0.1946249  0.92025499]]


## NumPy array math

Vectorization concept: 
NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements.

Examples of these:
- Square all items in array
- Add constants


And things you can do with two arrays
(caution on relative size and shapes allowed):
- Add two arrays
- Dot product
- Cross product


In [83]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [85]:
#Element-wise addition.
print("Element-wise addition:")
print(arr1 + arr2)

Element-wise addition:
[[ 6  8]
 [10 12]]


In [87]:
#Element-wise multiplication.
print("\nElement-wise multiplication:")
print(arr1 * arr2)


Element-wise multiplication:
[[ 5 12]
 [21 32]]


In [89]:
#Matrix multiplication.
#Maybe clarify that's the dot product of two arrays?
print("\nMatrix multiplication:")
print(np.dot(arr1, arr2))


Matrix multiplication:
[[19 22]
 [43 50]]


In [91]:
print(np.cross(arr1, arr2))

[-4 -4]


## NumPy Array Manipulation

### Flattening arrays

In [96]:
import numpy as np 
a = np.arange(8).reshape(2,4) 
print ('The original array:' )
print (a )
print ('\n') 

print ('After applying the flat function:' )
#Returns element corresponding to index in flattened array. 
a.flat[5]

The original array:
[[0 1 2 3]
 [4 5 6 7]]


After applying the flat function:


5

In [98]:
#Flattening.
a = np.arange(8).reshape(2,4) 

print ('The original array is:') 
print (a )
print ('\n')  
#Default is column-major. 

print ('The flattened array is:' )
print (a.flatten() )
print ('\n')  

print ('The flattened array in F-style ordering:') 
a.flatten(order = 'F')

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


The flattened array is:
[0 1 2 3 4 5 6 7]


The flattened array in F-style ordering:


array([0, 4, 1, 5, 2, 6, 3, 7])

In [100]:
#Raval.
a = np.arange(8).reshape(2,4) 

print ('The original array is:' )
a
print ('\n'  )

print( 'After applying ravel function:' )
a.ravel()  
print ('\n') 

print ('Applying ravel function in F-style ordering:') 
a.ravel(order = 'F')

The original array is:


After applying ravel function:


Applying ravel function in F-style ordering:


array([0, 4, 1, 5, 2, 6, 3, 7])

### Reshaping arrays

In [103]:
a = np.arange(8)
print ('The original array:')
a
print ('\n')

b = a.reshape(4,2)
print ('The modified array:')
b

The original array:


The modified array:


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [105]:
#Transpose.
a = np.arange(8).reshape(2,4) 

'The original array is:' 
a 
'\n'  

'After applying ravel function:' 
a.ravel()  
'\n' 

'Applying ravel function in F-style ordering:' 
a.ravel(order = 'F')

array([0, 4, 1, 5, 2, 6, 3, 7])

### Switching axes

In [108]:
#Roll Axis.
a = np.arange(8).reshape(2,2,2) 

'The original array:' 
a 
'\n'
#To roll axis-2 to axis-0 (along width to along depth). 

'After applying rollaxis function:' 
np.rollaxis(a,2)  

#To roll axis 0 to 1 (along width to height).
'\n' 

'After applying rollaxis function:' 
np.rollaxis(a,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [110]:
#Swap axis.
a = np.arange(8).reshape(2,2,2) 

print ('The original array:') 
print (a) 
print ('\n')  
#Now swap numbers between axis 0 (along depth) and axis 2 (along width). 

print ('The array after applying the swapaxes function:') 
print (np.swapaxes(a, 2, 0))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


The array after applying the swapaxes function:
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


### Joining arrays

Different ways

In [120]:
#Concatination.
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  
#Both the arrays are of same dimensions. 

print ('Joining the two arrays along axis 0:' )
print (np.concatenate((a,b)) )
print ('\n')  

print ('Joining the two arrays along axis 1:') 
print( np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [126]:
#Stacking.
a = np.array([[1,2],[3,4]]) 

print ('First Array:') 
print (a )
print ('\n')
b = np.array([[5,6],[7,8]]) 

print ('Second Array:') 
print (b) 
print ('\n')  

print ('Stack the two arrays along axis 0:' )
print (np.stack((a,b),0) )
print ('\n')  

print ('Stack the two arrays along axis 1:') 
print (np.stack((a,b),1))

First Array:
[[1 2]
 [3 4]]


Second Array:
[[5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [128]:
#Splitting arrays.
a = np.arange(9) 

print ('First array:' )
print (a )
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print( b )
print( '\n'  )

print ('Split the array at positions indicated in 1-D array:') 
b = np.split(a,[4,7])
print( b )

First array:
[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [ ]:
#Resize array.
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 
print ('\n')

print( 'The shape of first array:' )
print (a.shape )
print ('\n' ) 
b = np.resize(a, (3,2)) 

print ('Second array:' )
print (b) 
print ('\n')  

print ('The shape of second array:') 
print (b.shape )
print ('\n')  
# Observe that first row of a is repeated in b since size is bigger. 

print ('Resize the second array:' )
b = np.resize(a,(3,3)) 
print b

In [130]:
#Insert.
a = np.array([[1,2],[3,4],[5,6]]) 

print( 'First array:' )
a 
print ('\n')  

print ('Axis parameter not passed. The input array is flattened before insertion.')
np.insert(a,3,[11,12]) 
print ('\n')  
print ('Axis parameter passed. The values array is broadcast to match input array.')

print ('Broadcast along axis 0:') 
np.insert(a,1,[11],axis = 0) 
print ('\n'  )

print ('Broadcast along axis 1:' )
np.insert(a,1,11,axis = 1)

First array:


Axis parameter not passed. The input array is flattened before insertion.


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:


Broadcast along axis 1:


array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

## Very useful NumPy functions and methods

Ones that look at whole array:
- where()
- sort()
- min()
- max()
- mean()
- count()

- ??unique()


Ones that look at specific elements in the array:
- maximum()

#### Some to check things in arrays  
np.isnan

Functions that deal with nan values.

In [147]:
a = np.arange(10)
>>> a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [151]:
np.where([[True, False], [True, True]])

(array([0, 1, 1], dtype=int64), array([0, 0, 1], dtype=int64))

In [153]:
x, y = np.ogrid[:3, :4]
>>> np.where(x < y, x, 10 + y)

array([[10,  0,  0,  0],
       [10, 11,  1,  1],
       [10, 11, 12,  2]])

In [155]:
a = np.array([[0, 1, 2],
...               [0, 2, 4],
...               [0, 3, 6]])
>>> np.where(a < 4, a, -1) 

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

In [157]:
a = np.array([[1,4],[3,1]])
>>> np.sort(a)     

array([[1, 4],
       [1, 3]])

In [159]:
np.sort(a, axis=None) 

array([1, 1, 3, 4])

In [161]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [163]:
array1 = np.array([10, 12, 14, 11, 5])

#Return the largest element. 
maxValue= np.max(array1)

print(maxValue)

14


In [165]:
array = np.array([[10, 17, 25], 
                  [15, 11, 22]])
                  
#Return the largest element of the flattened array.
maxValue = np.max(array)

print('The largest element in the flattened array: ', maxValue)

#Return the largest element in each column.
maxValue = np.max(array, axis = 0)

print('The largest element in each column (axis 0): ', maxValue)

#Return the largest element in each row.
maxValue = np.max(array, axis = 1)

print('The largest element in each row (axis 1): ', maxValue)

The largest element in the flattened array:  25
The largest element in each column (axis 0):  [15 17 25]
The largest element in each row (axis 1):  [25 22]


In [167]:
array1 = np.array([[10, 17, 25], 
                  [15, 11, 22], 
                  [11, 19, 20]])

#Create an empty array.
array2= np.array([0, 0, 0])

#Pass the 'out' argument to store the result in array2.
np.max(array1, axis = 0, out = array2)

print(array2)

[15 19 25]


In [169]:
rray1 = np.array([[10, 17, 25], 
                   [15, 11, 22]])
print('Dimensions of original array: ', array1.ndim)

maxValue = np.max(array1, axis = 1)

print('\n Without keepdims: \n', maxValue)
print('Dimensions of array: ', maxValue.ndim) 

#Set keepdims to True to retain the dimension of the input array.
maxValue = np.max(array1, axis = 1, keepdims = True)

print('\n With keepdims: \n', maxValue)
print('Dimensions of array: ', maxValue.ndim)

Dimensions of original array:  2

 Without keepdims: 
 [25 22 20]
Dimensions of array:  1

 With keepdims: 
 [[25]
 [22]
 [20]]
Dimensions of array:  2


In [171]:
#Max value > initial, returns max value.
array1 = np.array([[10, 25, 17, 16, 14]])
maxValue = np.max(array1, initial = 6)
print(maxValue)

#Max value < initial, returns initial.
array2 = np.array([[10, 25, 17, 16, 14]])
maxValue = np.max(array2, initial = 26)
print(maxValue)

#In case of an empty array, initial value is returned.
array3 = np.array([])
maxValue = np.max(array3, initial = 5)
print(maxValue)

25
26
5.0


In [173]:
rray1 = np.array([10, 12, 14, 11, 5])

#Return the smallest element. 
minValue= np.min(array1)

print(minValue)

# Output: 5

10


In [175]:
array = np.array([[10, 17, 25], 
                  [15, 11, 22]])
                  
#Return the smallest element of the flattened array.
minValue = np.min(array)

print('The smallest element in the flattened array: ', minValue)

#Return the smallest element in each column.
minValue = np.min(array, axis = 0)

print('The smallest element in each column (axis 0): ', minValue)

#Return the smallest element in each row.
minValue = np.min(array, axis = 1)

print('The smallest element in each row (axis 1): ', minValue)

The smallest element in the flattened array:  10
The smallest element in each column (axis 0):  [10 11 22]
The smallest element in each row (axis 1):  [10 11]


In [177]:
array1 = np.array([[10, 17, 25], 
                   [15, 11, 22], 
                   [11, 19, 20]])

#Create an empty array.
array2= np.array([0, 0, 0])

#Pass the 'out' argument to store the result in array2.
np.min(array1, axis = 0, out = array2)

print(array2)

[10 11 20]


In [179]:
array1 = np.array([[10, 17, 25], 
              	    [15, 11, 22]])

print('Dimensions of original array: ', array1.ndim)

minValue = np.min(array1, axis = 1)

print('\n Without keepdims: \n', minValue)
print('Dimensions of array: ', minValue.ndim) 

#Set keepdims to True to retain the dimension of the input array.
minValue = np.min(array1, axis = 1, keepdims = True)

print('\n With keepdims: \n', minValue)
print('Dimensions of array: ', minValue.ndim)

Dimensions of original array:  2

 Without keepdims: 
 [10 11]
Dimensions of array:  1

 With keepdims: 
 [[10]
 [11]]
Dimensions of array:  2


In [181]:
import numpy as np

#Create an array.
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7])

#Calculate the mean of the array.
avg = np.mean(array1)

print(avg)

# Output: 3.5

3.5


In [77]:
#Create a 3D array.
array1 = np.array([[[1, 2], [3, 4]],                     
                    [[5, 6], [7, 8]]])

#Find the mean of entire array.
mean1 = np.mean(array1)

#Find the mean across axis 0.
mean2 = np.mean(array1, 0)

#Find the mean across axis 0 and 1.
mean3 = np.mean(array1, (0, 1))

print('\nMean of the entire array:', mean1)
print('\nMean across axis 0:\n', mean2)
print('\nMean across axis 0 and 1', mean3)


Mean of the entire array: 4.5

Mean across axis 0:
 [[3. 4.]
 [5. 6.]]

Mean across axis 0 and 1 [4. 5.]


In [183]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#By default int is converted to float.
result1 = np.mean(arr)

#Get integer mean.
result2 = np.mean(arr, dtype = int)

print('Float mean:', result1)
print('Integer mean:', result2)

Float mean: 3.5
Integer mean: 3


In [185]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#Keepdims defaults to False.
result1 = np.mean(arr, axis = 0)

#Set keepdims to True.
result2 = np.mean(arr, axis = 0, keepdims = True)

print('Original Array Dimension:', arr.ndim)
print('Mean without keepdims:', result1, 'Dimensions', result1.ndim)
print('Mean with keepdims:', result2, 'Dimensions', result2.ndim)

Original Array Dimension: 2
Mean without keepdims: [2.5 3.5 4.5] Dimensions 1
Mean with keepdims: [[2.5 3.5 4.5]] Dimensions 2


In [187]:
#2D array.  
arr = ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz'] 
  
print ("arr : ", arr) 
  
print ("Count of 'tt'", np.char.count(arr, 'tt')) 
print ("Count of 'tt'", np.char.count(arr, 'tt', start = 0)) 
print ("Count of 'tt'", np.char.count(arr, 'tt', start = 8)) 

arr :  ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz']
Count of 'tt' [2 2 1 0]
Count of 'tt' [2 2 1 0]
Count of 'tt' [1 2 1 0]


In [189]:
#2D array.  
arr = ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz'] 
  
print ("arr : ", arr) 
  
print ("Count of 'Aa'", np.char.count(arr, 'Aa')) 
print ("Count of 'Aa'", np.char.count(arr, 'Aa', start = 8)) 

arr :  ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz']
Count of 'Aa' [1 1 1 1]
Count of 'Aa' [1 0 0 0]


In [191]:
np.unique([0,1,2,0,2,3,4,3,0,4])
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [193]:
x = np.array([[1, 1], [2,3], [3,4]])
>>> np.unique(x)
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [195]:
x = np.array(['o', 'p', 'y', 't', 'h', 'o', 'p'])
>>> u, indices = np.unique(x, return_index=True)
>>> u
np.array(['h', 'o', 'p', 't', 'y'], 
      dtype='<U1')
>>> indices
np.array([4, 0, 1, 3, 2])
>>> x[indices]
np.array(['h', 'o', 'p', 't', 'y'], 
      dtype='<U1')

array(['h', 'o', 'p', 't', 'y'], dtype='<U1')

In [197]:
x = np.array([0, 1, 2, 5, 2, 6, 5, 2, 3, 1])
>>> u, indices = np.unique(x, return_inverse=True)
>>> u
np.array([0, 1, 2, 3, 5, 6])

array([0, 1, 2, 3, 5, 6])

In [199]:
x = np.array([1,2,5,3,4,2,3,2,5,4])
>>> u, indices = np.unique(x, return_inverse=True)
>>> u
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

# Assignments

## Exercise 1)

## Exercise 2)

## Exercise 3)