# Solutions for Tutorial 3: Collection Data Types in Python


This notebook accompanies the Tutorial 3 notebook and shows some possible solutions for the Exercises at the end of the Tutorial

This tutorial was compiled for the PAARE project at South Carolina State University in partnership with Clemson University and the University of the Virgin Islands and funded by NSF.  (NSF grant AST  2319415)

* Original posting:
  * JCash 06-13-2025
* Last modification:
  * JCash 06-13-2025

###  Imports needed

It is always best practice to import the needed packages at the very top of the notebook. As a notebook is developed, you can always add to or take away from that cell. 

The cell should always be run before any other cells in the notebook and right after any changes to the import list are given. 

For this tutorial we will use NumPy.

In [1]:
import numpy as np

# Assignment



In [ ]:
#If you reopen the notebook to continue working on the assignments, you probable will need to rerun the import
import numpy as np

## Exercise 1)

1) Manually create a list containing the names of the eight major planets. 

2) Use the append method to add the names of at least three dwarf planets to your list. 

In [ ]:
# Create a list of the names of the planets.

# Use an append to add the names of at least three dwarf planets.

# Print out the full list at the end.


In [2]:
# Example Solution 2
# create a list of the names of the planets
SS = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

#use an append to add the names of the dwarf planets
SS.append('Pluto')
SS.append('Ceres')
SS.append('Eris')
SS.append('Haumea')

#print out the full list at the end
print(SS)

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres', 'Eris', 'Haumea']


For append you need to add each item one at a time.

In [3]:
# Example Solution 2
# create a list of the names of the planets
SS = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

#use an append to add the names of the dwarf planets
SS.append(['Pluto','Ceres','Eris','Haumea'])
#print out the full list at the end
print(SS)

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', ['Pluto', 'Ceres', 'Eris', 'Haumea']]


Note that in solution 2 the four dwarf planets were added as a single item which was a list of the four. 
We really wanted them as individual items.

In [4]:
# Example Solution 3
# create a list of the names of the planets
SS = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

#use an append to add the names of the dwarf planets
SS.extend(['Pluto','Ceres','Eris','Haumea'])
#print out the full list at the end
print(SS)

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres', 'Eris', 'Haumea']


As an alternative, `extend` is another list method that allows you to add a list of items as individual items.

**Getting Help**
If you tried to append multiple items at once you might have gotten ...

If you gogle 

## Exercise 2)

1) Use the internet to look up information on the eight major planets in our solar system.
2) Manually create a NumPy Array with the values for the mass of each major planet in units of kg.
3) Manually create a NumPy Array with the values for the radius of each major planet in units of m.
    - (You will want to put in the radius values in scientific notation not as integers) 
5) Using mathematical operations, create a new NumPy Array that holds the calculated values for the average density of each planet.
6) Create a 2D array with rows for the mass, radius, and density, where each column is for a planet.
7) Use slicing on the 2D array to get all of the values for the inner terrestrial planets.
8) Use slicing on the 2D array to get just the density values for the outer jovian planets.

In [ ]:
# Enter your code below.

In [ ]:
#Possible Solution 1 (note this one has an error)
#enter your code below

#in case imports haven't been run in the notebook
import numpy as np

#Step 1, values from NASA website
#add info on where I got it

# Step two, the create array for the planet masses
Pmass = np.array([3.3e+23,4.87e+24,5.97e+24,6.42e+23,1.89e+27,5.68e+26,8.68e+25,1.02e+26])
# Step three, Create the arrays for the Planet radius
Prad = np.array([2.44e+7,6.05e+7,6.37e+7,3.39e+7,7.15e+8,6.03e+8,2.55e+8,2.47e+8])

#Step 4, calculate density
Pvol = 4/3*(np.pi)*(Prad**2)
Pden = Pmass/Pvol
print(Pden)

#Step 5, create 2D array with mass, radius, and density as rows
full = np.stack([Pmass,Prad,Pden])
print(full)
print(full.shape)

#Step 6, 
print(full[:,0:3])

#Step 7
print(full[:,4:7])

Can you find the error in the code above?

How can we make the code and output easier to follow.

In [8]:
#Possible Solution 2
"""
This assignment worked with data about the planets to calculate the densities.

The data used came from:

We use the following variable names:
Pmass is a list of the mass of each planet in units of kg
Prad is a list of the radius of each planet in units of meters
Pvol is a list of the volumes of each planet calculated from the radius, assuming a sphere
Pden is a list of the average density of each planet in unit of kg/m^3
Ptable is a 2D np array 
"""


import numpy as np

#Step 1, values from NASA website
print('Values for this assignment were taken from a NASA Website.')

#Step two and three, create arrays for the mass and radius
Pmass = np.array([3.3e+23,4.87e+24,5.97e+24,6.42e+23,1.89e+27,5.68e+26,8.68e+25,1.02e+26])
Prad = np.array([2.44e+7,6.05e+7,6.37e+7,3.39e+7,7.15e+8,6.03e+8,2.55e+8,2.47e+8])

#Step 4, calculate density
Pvol = 4/3*(np.pi)*(Prad**3)
Pden = Pmass/Pvol
print('The densities are:')
print(Pden)

#Step 5, create 2D array with mass, radius, and density as rows
Ptable = np.stack([Pmass,Prad,Pden])
print('The full data is:')
print(Ptable)
print('The shape is:',Ptable.shape)

#Step 6, Use slicing on the 2D array to get the values for the inner terrestrial planets
print('The terrestrial planets')
#We want all of the rows, but just the four opening columns so I need from 0 to 4
print(Ptable[:,0:4])

#Step 7 Use slicing on the 2D array to get just the density values for the outer jovian planets.
print('The Jovian planets')
#We want all of the rows, but just the columns starting with Jupiter in index 4
print(Ptable[:,4:])

Values for this assignment were taken from a NASA Website.
The densities are:
[5.42320288 5.25018042 5.51400842 3.93411748 1.2343976  0.61845455
 1.24971383 1.61592315]
The full data is:
[[3.30000000e+23 4.87000000e+24 5.97000000e+24 6.42000000e+23
  1.89000000e+27 5.68000000e+26 8.68000000e+25 1.02000000e+26]
 [2.44000000e+07 6.05000000e+07 6.37000000e+07 3.39000000e+07
  7.15000000e+08 6.03000000e+08 2.55000000e+08 2.47000000e+08]
 [5.42320288e+00 5.25018042e+00 5.51400842e+00 3.93411748e+00
  1.23439760e+00 6.18454551e-01 1.24971383e+00 1.61592315e+00]]
The shape is: (3, 8)
The terrestrial planets
[[3.30000000e+23 4.87000000e+24 5.97000000e+24 6.42000000e+23]
 [2.44000000e+07 6.05000000e+07 6.37000000e+07 3.39000000e+07]
 [5.42320288e+00 5.25018042e+00 5.51400842e+00 3.93411748e+00]]
The Jovian planets
[[1.89000000e+27 5.68000000e+26 8.68000000e+25 1.02000000e+26]
 [7.15000000e+08 6.03000000e+08 2.55000000e+08 2.47000000e+08]
 [1.23439760e+00 6.18454551e-01 1.24971383e+00 1.61592315

## Exercise 3)

In this exercise, you are given a filename as a string. This file name contains information about the data contained in the file (a common practice in data science).

You are told that the file name has three parts separated by underscore characters `_`.

You need to:
- Split the string using the delimiter.
- Save the first part of the filename to a variable called `id` and convert it into an integer value.
- Save the second part of the filename to a variable called `period` and convert it into a float.
- Save the third part of the filename into a string variable called `ftype`.

In [ ]:
fname = '450119293_0.522044_lc.dat'

# Put your code below.


## Exercise 4)

Create a dictionary representing the stellar characteristics of the Sun.

1) Use the internet to look up the values for the Sun.
2) Think about which values are important for an astronomer.
3) Manually create a dictionary of the values.
4) Use the dictionary values to calculate the average density of the Sun from the radius and mass.



In [ ]:
# Insert your code here.
