<div class="alert alert-block alert-info">
<b>TBA:</b> jcash will improve text here

    I need to finish up the arrangement of the sections and then set the section numbers

    I need to create the assignments
</div>

# Tutorial 6: Further Introduction to NumPy 

**Still a draft version**

Sections of this notebook come from several other tutorial notebooks including but not limited to the Officialy Numpy Documentation at https://numpy.org/doc/stable/,  tutorials at the W3 school  (https://www.w3schools.com/python/numpy/default.asp), the Geeks for Geels website (https://www.geeksforgeeks.org/numpy/python-numpy/). the Krittika Tutorials, and additional sources.

This tutorial was compiled for the PAARE project at South Carolina State University in partnership with Clemson University and the University of the Virgin Islands and funded by NSF. (NSF grant AST  2319415)

* Originally posted
  * JCash June 25, 2025
* Last modified:
  * JCash July 1, 2025

## Overview

In this tutorial we will take a closer look at some of the powerful tools available within the NumPy (Numerical Python) module. We have already used numpy functions in several of the preceeding tutorials and will continue to use them in the future tutorials. 

From the NumPy website:
>NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.



Specifically in this tutorial:
* NumPy math operations
* Num Array Creation
* Array Manipulation
* Useful functions and methods in NumPy

> Note that NumPy and numpy are used interchangeably when describing the package. The official name is `NumPy`. For import statements, you must use the lower-case version `numpy`.

### Imports needed

Since NumPy is not built into Python, we need import the package to use the functions. NumPy is so commonly used that the shortened alias import statement of `import numpy as np` is standard. 

As a reminder, you only need to import the package once when you open a notebook, but it doesn't hurt to run that command multiple times in the notebook. If you save your notebook and come back to it later or interrupt the kernel, you will need to reimport the package. 


In [1]:
import numpy as np

## 1.0) NumPy math operations

In tutorial 2, used numpy functions for square roots, rounding, and trig functions. We also used the numpy constant `np.pi`. Another package called `math` has many similar functions which work well, but `numpy` is more powerful.

A full listing of the available math functions can be found at:
https://numpy.org/doc/stable/reference/routines.math.html

The math functions in numpy can act on a single number (int or float) or a numpy array of numbers. This makes the numpy functions faster when applied to data science.

### 1.1) Review of Some Math Operations

Below are a few of the math operations introduced in previous tutorials. 

In [ ]:
print('The square root of 25 is',np.sqrt(25)) 
print('The number 2 to the 11 power can be found by numpy',np.power(2,11))
print('We can round off a number using numpy: 4.6874 becomes',np.round(4.6874,2))
print('The cosine of pi is', np.cos(np.pi))

### 1.2) Trig and Angular Conversion Functions


NumPy has the full range of Trigonometric, inverse trig, and Hyperbolic functions.

In general, the functions assume angles in radians, but there are also functions to change between degrees and radians.

See below for some examples.

In [ ]:
# Example trig functions
print('Sine of pi/2 = ', np.sin(np.pi/2))
print('The inverse cosine of 0.5 =',np.arccos(0.5))
print('The hyperbolic tangent of pi/2 =',np.tanh(np.pi/2))

In [ ]:
#This example shows the numpy function to change degrees to radians
angle_deg = 60
angle_rad = np.deg2rad(angle_deg)
print("an angle of ", angle_deg," degrees is equal to ", angle_rad," radians")

In [ ]:
#This example uses several functions together to get the inverse tangent in degrees with the correct quadrant.
x = 3
y = 4
print(np.degrees(np.arctan2(y,x)))
print(np.degrees(np.arctan2(y,-x)))


In [ ]:
angle_rad = 1.3
angle_deg = np.rad2deg(angle_rad)
print("an angle of ", angle_rad," radians is equal to ", angle_deg," degrees")

### 1.3) Rounding functions

There is a set of numpy functions for various rounding processes with more options than the built-in round function. 

* `np.round(x,d)` rounds off a float to the given decimals and returns it as a float value 


In [ ]:
#Various examples
x = 450.598756
print('This is the built-in round function',round(x),type(round(x)))
print('This is the numpy round function',np.round(x,0),type(np.round(x,0)))
print('This is the numpy round function with three digits',np.round(x,3),type(np.round(x,3)))
print('The numpy fix function rounds down',np.fix(x),type(np.fix(x)))
print('The numpy floor function rounds down',np.floor(x),type(np.floor(x)))
print('The numpy ceiling function rounds up',np.ceil(x),type(np.ceil(x)))



In [ ]:
print("In this example, you can get the decimal part of a floating point number")
x = 450.598756
print(x-np.floor(x))

### 1.4) Other functions in NumPy

The full range of mathematical functions to operate on single values in numpy is beyond the scope of this tutorial, but I list some of the categories below.

* exponents
* logarithms
* complex numbers
* miscallaneous

In [ ]:
import numpy as np

## 2.0) Creating NumPy arrays

NumPy is particularly powerful due to its ability to deal with arrays of data instead of just single values. 

We have explored basic array creation in previous tutorials, but show some additional methods here. 

### 2.1) Manual array creation

As a reminder from previous tutorials, the basic `np.array()` function creates a numpy array.

* 0 D arrays are single values.
* 1 D arrays are a set of values in a row.
    * it has a single index for the position in the row 
* 2 D arrays are a table of values (with rows and columns).
    * it has two indexes the first for the row and the second for the column.
* 3 D arrays are like a cube of data with a table at each layer.
    * it has three indexes, the first for the layer, then the row, then the column.

You can get the number of dimensions using the method `.ndim` on the array.
You can get the shape with the `.shape` method.

Examples of each are shown below.

In [ ]:
# 0D arrays


arr = np.array(42)

print('The array is',arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)


In [ ]:
# 1D array

arr = np.array((1, 2, 3, 4, 5))
print('The array is',arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)

In [ ]:
#2D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('The array is',arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)

In [ ]:
#3D arrays.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6] ,[4, 5, 6]], [[1, 2, 3], [4, 5, 6],[1, 2, 3]]])

print('The array is')
print(arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)

In [ ]:
#Higher dimensional arrays.
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

### 2.2) Array creation from a list

If you already have data in a list, you can convert the list to an array as long as all items in the list are the same DataType.

In [ ]:
list = [3,7,2,6]
print('List is',list,type(list))

array = np.array(list)
print('Array is',array,type(array))

If the list has multiple DataTypes you can still convert it to an array but all of the values will be converted to the string DataType.

In [ ]:
list = [3.0,'7',2,6]
print('List is',list,type(list))

array = np.array(list)
print('Array is',array,type(array))

If you have multiple lists you can convert them to a 2D array with each list being a row of the 2D array. Note the arrays must have the same length to do this so that the rows have the same number of columns. 


In [ ]:
list1 = [3,7,2,6]
list2 = [4,2,8,7]

array = np.array([list1,list2])
print('Array is')
print(array)
print('Array shape is',array.shape)

### 2.3) Special Array Creation

Below are some special ways to create an array and fill the array with specific values or patterns

#### Zero arrays

This creates an array of the specified size with zero values at each location.

In [ ]:
# 1 D zeros array
a = np.zeros(5)
print("1D Zeros Array:")
print(a)

In [ ]:
#Creating an 2D array of zeros.
zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("2D Zeros Array:")
print(zeros_array)

#### Ones arrays

This creates an array with a value of 1 at each location. 

In [ ]:
#Creating an array of ones.
ones_array = np.ones((3, 2))  # 3 rows, 2 columns
print("\nOnes Array:")
print(ones_array)

#### Filled arrays

This creates an array with a value you choose at each location. You put in the shape first (as a tuple) and then give the value. 

This fill value can be a number or the `np.nan` (not a number). 


In [ ]:
full_array = np.full((3,2),25.)
print(full_array)

In [ ]:
full_array = np.full((3,2),np.nan)
print(full_array)

#### Ranged arrays

These functions create an array with evenly spaced values.

* `arange` is used for integer values
* `linspace` is used for decimal values

In [ ]:
#Ranged arrays
range_array = np.arange(20)
print(range_array)

In [ ]:
lin_array = np.linspace(1,2,5) #start at 1, stop at 2, include 5 values
print(lin_array)

#### Random arrays

These functions create an array with evenly spaced values.

* `np.random.randint` is used for integer values with a specified low, high, and size
* `np.random.rand` is used for decimal values between zero and 1

In [ ]:
#Creating an array with random values.
random_array = np.random.randint(4,8,(2, 3))  # between 4 and 8 with a shape of 2 rows, 3 columns
print("\nRandom Array:")
print(random_array)

In [ ]:
#Creating an array with random values.
random_array = np.random.rand(2, 3)  # 2 rows, 3 columns
print("\nRandom Array:")
print(random_array)

#### Identity matrix

This is a 2D square array with values of 1 on the diagonal and 0 everywhere else (useful in some linear algebra operations).

In [ ]:
ident = np.identity(4)
print(ident)

## 3.0) NumPy Array Math

You should recall from the earlier tutorial on Collection DataTypes that numpy arrays are different than lists in that they must all contain the same DataType and that it is designed for numerical DataTypes. This is required since numpy has many functions that do math which would not work with strings or varying DataTypes.

Vectorization concept: 
NumPy vectorization involves performing mathematical operations on entire arrays. This simplifies the code and speeds up the computations.

There are **element-wise** operations, where the operation is applied to each element individually without the need to explicilty call a loop over the array. It makes the code simplier and more readable as well as running faster than using a loop. 

There are **statistical functions** which calculate a single value for an array of values.

There are 

And things you can do with two arrays
(caution on relative size and shapes allowed):
- Add two arrays
- Dot product
- Cross product


### 3.1) Element-wise operations

You can use many numpy functions one array, where the operation is performed on each element.
 
Examples of Element-wise operations:
- Add the same constant to each value in the array.
- Square each item in the array
- Evaluation a calulcation using each value in the array individually.


Here we start by creating a range array and then showing the results of different mathematical calculations on the array.

In [ ]:
#Setting up the array of numbers
a = np.arange(10)
print('Original array: ', a)

In [ ]:
print('Adding a constant',a+2)

In [ ]:
print('Multiplying by a constant',a*10)

In [ ]:
print('Square of each value:',a**2)

In [ ]:
# Using a slope intercept equation for a line
m = 4.5
b = 3
print('Using an equation for a line, here is the y values:',m*a+b)

### 3.2) Boolean Operations

When Boolean comparison operations are used on arrays, the results can be very useful. The initial discussion here is expanded later in this tutorial in section 5.2 so searching and filtering array. 

In out previous introduction to the Boolean DataTypes `True` and `False`, we saw that we can generate these values using comparison operators. 

For example `3>5` becomes `False` but `5>3` becomes `True`.
These `True` and `False` conditions can be used to trigger conditional sections of code using if-else statements. 

When you apply a comparison operator to a numpy array, you get a new array populated with the `True` and `False` values at each index. 

Now we can use the result of that test comparison to do useful things such as select just the parts of the array that have the condition we want. Instead of having to access the array using a loop or with specific indices, we can grab just the values where our condition is `True`.

See the example below. 

In [ ]:
# Create a random integer array
xarr = np.random.randint(0,30,10)  #10 random values between 0 and 30
print('\n The random array is')
print(xarr)

# create a new variable which is the result of the comparison to look at values greater than 15
test_result = xarr > 15
print('\nThe result is')
print(test_result)


yarr = xarr[test_result]
print('\nThe new yarr with just the large values is')
print(yarr)
print()

### 3.3) Statistical functions

Numpy has many important numpy functions in data science and statistical analysis. These functions work on arrays instead of working element-wise. Obviously, these can only be used with arrays containing numbers (not strings). 

* `np.mean`   This gives the mean (or average) value from the whole array.
* `np.median` This gives the median (or middle) value from the whole array.
* `np.min`    This finds the smallest value in the array.
* `np.max`    This finds the largest value in the array.
* `np.sum`    This adds up all of the values in the array.
* `np.sdv`    This gives the standard deviation of the array values.


In [ ]:
# First we create some arrays to use for our analysis
a = np.arange(10)  #This array ranges from 0 to 9
b = a *10+1        #This array ranges from 1 to 91
c = np.random.rand(10)  #This create an array of random floats between 0 and 1

print('a\n',a)

print('b\n',b)

print('c\n',c)

In [ ]:
#Getting mean of all numbers in 'a'.
print("mean a:",np.mean(a))
print("mean b:", np.mean(b))
print("mean c:", np.mean(c))


In [ ]:
#Getting Median of all numbers in 'a'.
print("Median a:",np.median(a))
print("Median b:", np.median(b))
print("Median c:", np.median(c))


In [ ]:
#Getting Minimum of all numbers in each array.
print("Minimum a:",np.min(a))
print("Minimum b:", np.min(b))
print("Minimum c:", np.min(c))


In [ ]:
#Getting Maximum of all numbers in each array.
print("Maximum a:",np.max(a))
print("Maximum b:", np.max(b))
print("Maximum c:", np.max(c))


In [ ]:
#Getting sum of all numbers in in each array.
print('Sum of values in a:',np.sum(a))
print('Sum of values in b:',np.sum(b))
print('Sum of values in c:',np.sum(c))


In [ ]:
#Getting Standard Deviation of all numbers in the arrays
print('SD in a:',np.std(a))
print('SD in b:',np.std(b))
print('SD in c:',np.std(c))


---
**Statistics on rows or columns of a 2D array**

If you use any of the above statistics functions on a 2D array, it will consider all values in all rows and columns of the array. 

Sometimes you may want the statistics for each row or column separately. NumPy can do this by specifying the axis in the statistics function call. 

`axis = 0` represents a comparison for values in each column
`axis = 1` represents a comparision for values in each row

In [ ]:
array = np.array([[10, 17, 25], 
                  [15, 11, 22]])

print('The 2D array is: \n',array,'\n')
#Return the largest element of the flattened array.
maxValue = np.max(array)

print('The largest element in the flattened array: ', maxValue)

#Return the largest element in each column.
maxValue = np.max(array, axis = 0)

print('The largest element in each column (axis 0): ', maxValue)

#Return the largest element in each row.
maxValue = np.max(array, axis = 1)

print('The largest element in each row (axis 1): ', maxValue)

### 3.4) Math with multiple arrays

You can also do **element-wise** math operations with numpy arrays. In most cases, the arrays must be the same size for these operations to work. 

In this case, the first value from the first array is matched with the first value from the second array, and then the math operation is done, returning a new value at that first position.

The examples shown below include:
* addition of arrays
* subtraction of arrays
* multiplication of arrays
* Division of arrays

You can even construct equations that use more complicated combinations of arrays as variables. 



In [ ]:
#Setting up the arrays

a = np.arange(10)  #This array ranges from 0 to 9
b = np.arange(20,40,2) #This array ranges from 20 to 40 in steps of 2
print('array a', a)
print('array b', b)

In [ ]:
print("Adding the arrays", a+b)
print("Subtracting the arrays", a-b)

In [ ]:
print("Multiplying the arrays", a*b)

In [ ]:
#Performing division using numpy functions.
div_ans = np.divide(a, b)
print(div_ans)

In [ ]:
#Performing division using numpy functions.
div_ans = b/a
print(div_ans)

#Note this one will give a warning since you divided by zero for the first index. The value of inf is the result.

In [ ]:
#Performing subtraction using arithmetic operator.
temp = a*b
result = (temp+10)/b -5
print("A more complicated math equation")
print(result)

In [ ]:
#Performing power of one array to itself ( a to the power of a)
pow_ans = np.power(a, a)
print(pow_ans)

### 3.5) Matrix math

2D arrays are similar to the mathematical concept of a matrix, and NumPy has several matrix functions built in.

To illustrate matrix math, we need to have 2D arrays in several shapes. The next cell creates those arrays. 
Some of the code in that cell will be explained later in this tutorial for array manipulation.

* `arr1` 1D array with 3 values
* `arr2` 1D array with 3 values
* `arr3` 1D array with 2 values
* `arr4` 1D array with 2 values
* `arr5` 1D array with 6 values
* `arr6` 2D array with 2 rows and 3 columns
* `arr7` 2D array with  3 rows and 2 columns

In [ ]:
arr1 = np.arange(3) +3
arr2 = np.arange(2) +4
arr3 = np.arange(6) 
arr4 = np.reshape(arr3,(2,3))
arr5 = np.reshape(arr3,(3,2))

In [ ]:
print('Matrix 1 \n',arr1)
print('Matrix 2 \n',arr2)
print('Matrix 3 \n',arr3)
print('Matrix 4\n',arr4)
print('Matrix 5\n',arr5)


#### Element wise multiplication
---
We already saw that you can do Element-wise multiplication of two arrays that are the same shape. 

If you multiply a 1D array by a 2D array with the same number of columns, then each row of the 2D array is multiplied by the elements of the 1D array. 

This is sometimes referred to as **broadcasting**. 

In [ ]:
# Arrays with 3 columns each
print('Array 1 multiplied by Array 1')
print(arr1*arr1,'\n')

print('Array 1 multiplied by Array 4')
print(arr1*arr4,'\n')

In [ ]:
#Arrays with 2 columns each
print(arr2*arr5)

---
**Warning**
If the arrays don't have the same number of columns, there will be a ValueError indicating the shape incompatibility.

The example below with give an error of this type

In [ ]:
print('Trying to multiply 3 columns by atwo column array')
print(arr1*arr5)

#### Matrix multiplication

Matrix multiplication is **not** element-wise. Instead, each element in the result is the **dot product** of a row from the first matrix and a column from the second.

NumPy has two ways to call this:
* `np.matmul()`
* `np.dot()`

For most cases the two functions give the smae result, but `np.matmul` is more stable for higher order matrices.


We'll walk through a clear example to show exactly what that means.

We will multiply a 2×3 matrix `A` with a 3×2 matrix `B`.



In [ ]:
# Matrix A (2x3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matrix B (3x2)
B = np.array([
    [10, 11],
    [20, 21],
    [30, 31]
])


print('Matrix A: \n')
print(A,'\n')
print('Matrix B: \n')
print(B,'\n')

print('Matrix multiplicaton result: \n')
print(np.matmul(A,B))

**Step by step behind the scenes** 

Step 1: First row of A • First column of B

[1 2 3] • [10 20 30] = (1×10 + 2×20 + 3×30) = 140

Step 2: First row of A • Second column of B

[1 2 3] • [11 21 31] = (1×11 + 2×21 + 3×31) = 146

→ First row of result = [140 146]

Step 3: Second row of A • First column of B

[4 5 6] • [10 20 30] = (4×10 + 5×20 + 6×30) = 320

Step 4: Second row of A • Second column of B

[4 5 6] • [11 21 31] = (4×11 + 5×21 + 6×31) = 335

→ Second row of result = [320 335]

**Other Matrix math operations**

Other Matrix operations are included in the NumPy package but not covered in this tutorial.

Some examples are:
* inverse
* determinate
* eigenvalues
* eigenvectors
* systems of linear equations



## 4.0) NumPy Array Manipulation

### 4.1)  Reshaping arrays

If you have an array with N items total, then you can reshape it into an form where the total items is still N.

For example:
 * A 1D array with 8 items can be reshaped into
     * A 2D array with 2 rows and 4 columns
     * A 2D array with 4 rows and 2 columns
     * A 2D array with 8 rows and 1 columns 
 * A 2D array with a shape of (3,4) can be reshaped into
     * A 2D array with a shape of (4,3)
     * A 2D array with a shape of (6,2)
     * A 2D array with a shape of (2,6)
     * A 1D array with a length of 12 items

In [ ]:
a = np.arange(8)
print ('The original array with 8 items:')
print(a)
print ('\n')

b = a.reshape(4,2)
print ('The modified to 4 rows and 2 columns:')
print(b)
print ('\n')

print ('The modified to 2 rows and 4 columns:')
print(a.reshape(2,4))


### 4.2) Flattening arrays

If you have a 2D array and want to turn it into a 1D array, you have several options.

The standard way is the `.flatten method` which creates one long array that starts with the first row, goes through all of the columns, and then gets the next row. 

If you use the `.flatten(order='F')` syntax, it gets the first column, goes through all of the rows and then gets the next column. It is called the `F` order since this was the standard way in fortran. 

In [ ]:
import numpy as np 
a = np.arange(8).reshape(2,4) 
print ('The original array:' )
print (a )
print ('\n') 

print ('After applying the flatten function:' ) 
print("The flattened array:")
b = a.flatten()
print(b)

In [ ]:
#Flattening.
a = np.arange(8).reshape(2,4) 

print ('The original array is:') 
print (a )
print ('\n')  
#Default is column-major. 

print ('The flattened array in F-style ordering:') 
a.flatten(order = 'F')

In [ ]:
#Raval.
a = np.arange(8).reshape(2,4) 

print ('The original array is:' )
print(a)
print ('\n'  )

print( 'After applying ravel function:' )
print(a.ravel())  
print ('\n') 

print ('Applying ravel function in F-style ordering:') 
a.ravel(order = 'F')

### 4.3) Transpose and Other Axes Manipulation

The numpy function `transpose` takes a 2D input array and flips the rows and columns. 

An array with a shape of 2 rows and 3 columns, will become an array with a shape of 3 rows and 2 columns.

But unlike reshape, the values are moved. So the element that was originally in the row 0, column 2 position will now be in the row 2, column 0 position.


In [ ]:
a = np.arange(6).reshape(2,3)
print('Original Matrix \n',a)
print('Transposed Matrix \n',np.transpose(a))

The numpy function `squeeze` will reduce the dimensions of an ND array if one or more of the dimensions have a size of 1. 

In the example below, the x array is a 3D matrix, with one layer, 3 rows,and 1 column.
After squeezing it, we get a 1D array with 3 items. 

This can be useful if you are extracting a subset of data from a larger dimensional data structure. 

In [ ]:
x = np.array([[[0], [1], [2]]])
print('Original array \n',x)
print('Original shape',x.shape)

print('\n after the squeeze')
y = np.squeeze(x)
print(y)
print('Shape of new array', y.shape)

When working with larger dimensional data sets, there are a variety of functions and methods that can transform the ND array by swapping or rolling axes that go beyond the scope of this tutorial.

### 4.4) Joining arrays


**Needs revision**

Topics to include:
- 1D join into longer 1D array
- multiple 1D, join with each as a row
- multiple 1D, join with each as a column
- multiple 2D, join by adding extra columns
- multiple 2D, join by adding new rows

In [18]:
x = np.arange(5)
y = x+10
print('x array is:', x)
print('y array is:', y)

x array is: [0 1 2 3 4]
y array is: [10 11 12 13 14]


In [19]:
b = np.array([x,y])
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [20]:
c = b.transpose()
c

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14]])

In [21]:
rowarray = np.stack([x,y],axis=0)
rowarray

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [22]:
colarray = np.stack([x,y],axis=1)
colarray

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14]])

In [23]:
np.hstack([b,b])

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [25]:
np.hstack([c,c])

array([[ 0, 10,  0, 10],
       [ 1, 11,  1, 11],
       [ 2, 12,  2, 12],
       [ 3, 13,  3, 13],
       [ 4, 14,  4, 14]])

In [24]:
np.vstack([b,b])

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [26]:
np.vstack([c,c])

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14]])

In [2]:
#Concatenation.
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  
#Both the arrays are of same dimensions. 

print ('Joining the two arrays along axis 0:' )
print (np.concatenate((a,b)) )
print ('\n')  

print ('Joining the two arrays along axis 1:') 
print( np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Stacking.
a = np.array([[1,2],[3,4]]) 

print ('First Array:') 
print (a )
print ('\n')
b = np.array([[5,6],[7,8]]) 

print ('Second Array:') 
print (b) 
print ('\n')  

print ('Stack the two arrays along axis 0:' )
print (np.stack((a,b),0) )
print ('\n')  

print ('Stack the two arrays along axis 1:') 
print (np.stack((a,b),1))

In [ ]:
#Splitting arrays.
a = np.arange(9) 

print ('First array:' )
print (a )
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print( b )
print( '\n'  )

print ('Split the array at positions indicated in 1-D array:') 
b = np.split(a,[4,7])
print( b )

In [ ]:
#Resize array.
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 
print ('\n')

print( 'The shape of first array:' )
print (a.shape )
print ('\n' ) 
b = np.resize(a, (3,2)) 

print ('Second array:' )
print (b) 
print ('\n')  

print ('The shape of second array:') 
print (b.shape )
print ('\n')  
# Observe that first row of a is repeated in b since size is bigger. 

print ('Resize the second array:' )
b = np.resize(a,(3,3)) 
print (b)

In [3]:
#Insert.
a = np.array([[1,2],[3,4],[5,6]]) 

print( 'First array:' )
print(a) 
print ('\n')  

print ('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a,3,[11,12]) )
print ('\n')  
print ('Axis parameter passed. The values array is broadcast to match input array.')

print ('Broadcast along axis 0:') 
print(np.insert(a,1,[11],axis = 0) )
print ('\n'  )

print ('Broadcast along axis 1:' )
np.insert(a,1,11,axis = 1)

First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:


array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

### 4.5) deleting rows or columns from a 2D array

`np.delete(arrname,irow,axis=0)`

`np.delete(arrname,icol,axis=1)`


In [ ]:
#Add code here

## 5.0) Very useful NumPy functions and methods

Ones that look at whole array:

- sort()
- count()
- unique()
- where()




### 5.1) Sorting arrays

Sorting a 1D array of numerical values is very easy with the `np.sort()` function.

The default way to use this call is `newarr = no.sort(oldarr)`
Where the oldarr is the one you want to sort, and newarr is the new array with the values from oldarr in numerical order. 

The array is automatically sorted in ascending order, but you can use the array manipulation `np.flip()` to reverse the order after sorting.

In [ ]:
arr_rand = np.random.randint(0,100,20)  #make a random array of 20 integers between 0 and 100
print('Random array: \n',arr_rand)

arr_sort = np.sort(arr_rand)
print('Sorted array: \n',arr_sort)

print('Flipped sorted array: \n',np.flip(arr_sort))

---
When sorting a 2D array, you can sort the order of the rows while keeping the row values together.

This is a two step process, where you first use the `.argsort` method to get a list of the indicies for the sorted order and then rearrange the rows in that order.

The example below shows how to sort the rows of a 2D table by the values in the 0 index column. 

Since the values in the 0 index column are (9,4,7) you would want the row with the value 4 first, then the row with the value 7 and finally the row with the value 9. 

In [ ]:
#First assign a 2D array

arr = np.array([[9, 2, 3],
                [4, 5, 6],
                [7, 0, 5]])
print('Random table: \n',arr,'\n')

#Extract the index 0 column and pass that to the argsort method
sorted_indices = arr[:, 0].argsort()
print('The rows should be rearranged in the following index order:,\n',sorted_indices,'\n')

#Then sort the table with the rows in that order
sorted_arr = arr[sorted_indices]
print('Sorted table: \n',sorted_arr,'\n')

How would you sort the table using the values in the index 1 column?

Use the space below to test the coding yourself.

In [ ]:
#Try sorting by the second column here


### 5.2) Searching and Filtering

We saw in Section 3.2 of this tutorial, that we can do a comparison operator on a NumPy array to create an array of Boolean `True False` values. 

The boolean array can be used for selection of specific parts of an array, for choosing between options for analysis, or other related searching and filtering options. 

The array of boolean values can be saved into a variable name to use multiple times, or the condition code can be placed into another function. 


**Note** I have seen some documentation that refers to these conditional boolean arrays as "masks" but in the opposite sense of the official numpy masks (where `True` represents a value you want to ignore). 

For the following sections, we will assume that `True` represents a value we want. 

---
**extract**

A numpy function to extract elements from an array where is specific condition holds True is `np.extract()`.

The syntax is `np.extract(condition,arr)` where the condition is the boolean expression and arr is the array. 

In the example below, only the values >= 0 are included in the output 

In [ ]:
# a is the full array
a = np.array([9, 3, -1, 2, -7, 8, 0])
print('Array a is:',a,"with the length of", len(a))

# b is the shortened array choosen from a
b= np.extract(a >=0,a)
print('Array b is:',b,"with a legnth of",len(b))
print()


When creating the conditions, you can use a mixture of arrays. For example you can use the values in one array to determine which elements to select from another array. 

For example, you may have one array with a set of times, and another array with fluxes. You could use the values in the time array to determine the condition but then extract those same elements from the flux array. 

The example below is a simplified example. In this case we consider a hypothetical situation where you have data for a whole range of times but you only trust the middle times. You may not know the indicies to select by slicing, but you know the time values that are okay. 



In [ ]:
#Set up an array of times 
time = np.round(np.linspace(0,10,20),2)
print('times',time)
flux = np.array([189.0, 186.0, 6.211, 8.316, 10.421, 12.526, 14.632, 16.737, 
              18.842, 20.947, 23.053, 25.158, 27.263, 29.368, 31.474, 
              33.579, 35.684, 37.789, 112.0, 113.0])
print('fluxes',flux)

#define a condition where the middle times are considered valid, but you want to neglect the start and end
midrange = (t > 2) & (t < 8)
print('midrange condition')
print(midrange)

#select out the midrange values
tok = np.extract(midrange,time)
fok = np.extract(midrange,flux)

print(tok,fok)

---

The `np.where()` function is a powerful tool used for conditional selection and manipulation of arrays. The function allows you to search, filter, and apply conditions to elements of an array, returning specific elements based on the condition provided.  

In its simplest form `np.where(condition)`, the function returns a tuple where the first item is a list of indices where the expression is true. 

The `condition` is typically a comparison operator on the array of the form `arr > 3` or `arr == 0`

If you need the list of indices, you can select the 0th index from the tuple. This is shown in the examples below.



In [ ]:
a = np.arange(10) +3
print('a array is:\n', a,'\n')

ind = np.where(a > 6)
print('The indices where the array value is greater than 6 are: ')
print(ind[0],'\n')

print('Selecting just the ones where the condition is true: \n', a[ind])

---
**Empty search results**
If the condition you are searching for is not found in an array, then you will get an empty list.



In [ ]:
a = np.arange(10)
print('a array is:\n', a,'\n')

ind = np.where(a < -1)
print('The indexes where the array value is less than 5 are: \n')
print(ind,'\n')

print('Flattening the output gives: \n', ind[0])

--- 
Where can also be used to replace values where a particular condition is met. 

In this form, the general format is `np.where(expression, x, y)`
Where the expression is True, it returns the corresponding values from x and when the expression is False, it returns the corresponding values from y.

In the example below, there is an array with negative and positive values. The `np.where` function is used to keep the values greater than or equal to zero with the original array values and replace the negative values with `np.nan`.

The second example compares two arrays. Where the array 1 value is larger it uses that value, but where the array 2 value is larger it uses that value

In [ ]:
x = np.array([9, 3, -1, 2, -7, 8, 0])

xnan = np.where(x >= 0, x , np.nan)

print(xnan)

In [ ]:
# Create two arrays of integers
array1 = np.array([3, 10, 7, 4, 12])
array2 = np.array([5, 6, 9, 8, 2])

# Use numpy.where to select the highest value at each index
max_values = np.where(array1 > array2, array1, array2)

# Print the results
print("Array 1:", array1)
print("Array 2:", array2)
print("Max at each index:", max_values)

In [ ]:
# Create two arrays
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([100, 150, 200, 250, 300])

# Use np.where() to select elements from arr1 where the condition is true, and arr2 otherwise
result = np.where(arr1 > 20, arr1, arr2)
print(result)

As another example, I used the np.where() function to create the flu arrays where the initial values were not trustworthy using the code below. See if you can follow what it is doing.

In [ ]:
#Set up an array of times 
t = np.linspace(0,10,20)
print('times',t)

# Create some reasonable linear flux values
f = t*4+2
print('fluxes',f)

# Create some high random values
ran = np.random.randint(100,200,20)
print('random',ran)


#define a condition where the middle times are considered valid, but you want to neglect the start and end
midrange = (t > 1) & (t < 9)
print('midrange condition')
print(midrange)

# Select okay values from the f array and the edge values from the random array
flux = np.where(midrange,f,ran)

#Create output that is easier to cut and paste into a cell to define the flu array.
flux_short = np.round(flux,3)
print(flux_short.tolist())

---
**Masked Arrays**

When you have specific data values in an array or table that are missing or invalid. There may be times when you want to keep all of the data values but you only want to consider the valid data points in your analysis. In this case, you can create a mask.  When an element of the mask is False, the corresponding element of the associated array is valid and is said to be unmasked. When an element of the mask is True, the corresponding element of the associated array is said to be masked (invalid).

Numpy has additional functions within the `numpy.ma` package that allow you to create a masked array (the array and mask are packaged together). 

Additional information is available at:
https://numpy.org/doc/stable/reference/maskedarray.generic.html

### 5.3) Unique

If you have a list of items and want to know what unique values are in there, you can use the `np.unique()` function.

The input is an array and the output is the sorted unique elements (those at appear at least once in the array).

A simple example is shown below with an array of integers.


In [ ]:
arr = np.array([1, 2, 3, 2, 1, 5, 5, 4])
unique_elements = np.unique(arr)
print(f"Unique elements: {unique_elements}")


Below is another example where the array is a list of astronomical filter bands designated by a single letter. 
In this example, we are extracting out the filters and excluding the repeats.

In [ ]:
# Create a string array of filter band names (with repeats)
filters = np.array(['g', 'r', 'i', 'g', 'z', 'u', 'y', 'r', 'i', 'i'])

# Find the unique filter names
unique_filters = np.unique(filters)

# Print the results
print("Original filter array:", filters)
print("Unique filter bands:", unique_filters)


In [ ]:
# Create a string array of filter band names (with repeats)
filters = np.array(['g', 'r', 'i', 'g', 'z', 'u', 'y', 'r', 'i', 'i'])

# Find the unique filter names
unique_filters, counts = np.unique(filters,return_counts=True)

# Print the results
print("Original filter array:", filters)
print("Unique filter bands:", unique_filters)
print("Counts:",counts)


---
**counts**

As an optional argument to `np.unique` you can have it count the number of times each filter band is listed. 


In [ ]:
arr = np.array([1, 2, 3, 2, 1, 4, 5, 4])
unique_elements = np.unique(arr)
print(f"Unique elements: {unique_elements}")

unique_elements, counts = np.unique(arr, return_counts=True)
print(f"Unique elements and their counts: {unique_elements}, {counts}")

### 5.4) Dealing with np.nan values

When a value of `np.nan` (Not A Number) appears in an array, it often requires special handling. Some of the functions below are used for these cases

* `np.isnan()`: Returns a boolean array indicating where NaN values are present.
* `np.nanmean()`, `np.nanmedian()`, `np.nansum()`, etc.: Functions that perform calculations while ignoring NaN values.
* `np.nan_to_num()`: Replaces NaN (and infinity) values with a specified number (often zero).

To show examples of these, we first create an array with some np.nan values. I use the example we created in the earlier section. 

In [ ]:
x = np.array([9, 3, -1, 2, -7, 8, 0])
xnan = np.where(x >= 0, x , np.nan)
print(xnan)


In [ ]:
#returns False if the element is a number, and True if the element is not a number
inan = np.isnan(xnan)
print(inan)

In [ ]:
# Find the sum the normal way
print('The normal np.sum gives:', np.sum(xnan))
print('The np.nansum gives:',np.nansum(xnan))

In [ ]:
# Find the sum the normal way
print('The normal np.mean gives:', np.mean(xnan))
print('The np.nanmean gives:',np.nanmean(xnan))

In [ ]:
#Replace the np.nan values with a zero
znan = np.nan_to_num(xnan,copy=True,nan=0)
print(znan)

In [ ]:
#Replace the np.nan values with a value of 100
ynan = np.nan_to_num(xnan,copy=True,nan=100)
print(ynan)

# Assignments


Not ready yet.

## Exercise 1)

## Exercise 2)

## Exercise 3)