<div class="alert alert-block alert-info">
<b>TBA:</b> jcash will improve text here

    I need to finish up the arrangement of the sections and then set the section numbers

    I need to create the assignments
</div>

# Tutorial 6: Introduction to NumPy 

**Still a draft version**

Sections of this notebook come from several other tutorial notebooks including but not limited to the Officialy Numpy Documentation at https://numpy.org/doc/stable/,  tutorials at the W3 school  (https://www.w3schools.com/python/numpy/default.asp), the Geeks for Geels website (https://www.geeksforgeeks.org/numpy/python-numpy/). the Krittika Tutorials, and additional sources.

This tutorial was compiled for the PAARE project at South Carolina State University in partnership with Clemson University and the University of the Virgin Islands and funded by NSF. (NSF grant AST  2319415)

* Originally posted
  * JCash June 25, 2025
* Last modified:
  * JCash June 25, 2025

## Overview

In this tutorial we will take a closer look at some of the powerful tools available within the NumPy (Numerical Python) module. We have already used numpy functions in several of the preceeding tutorials and will continue to use them in the future tutorials. 

From the NumPy website:
>NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.



Specifically in this tutorial:
* NumPy math operations
* Num Array Creation
* Array Manipulation
* Useful functions and methods in NumPy

> Note that NumPy and numpy are used interchangeably when describing the package. The official name is `NumPy`. For import statements, you must use the lower-case version `numpy`.

### Imports needed

Since NumPy is not built into Python, we need import the package to use the functions. NumPy is so commonly used that the shortened alias import statement of `import numpy as np` is standard. 

As a reminder, you only need to import the package once when you open a notebook, but it doesn't hurt to run that command multiple times in the notebook. If you save your notebook and come back to it later or interrupt the kernel, you will need to reimport the package. 


In [3]:
import numpy as np

## 1.0) NumPy math operations

In tutorial 2, used numpy functions for square roots, rounding, and trig functions. We also used the numpy constant `np.pi`. Another package called `math` has many similar functions which work well, but `numpy` is more powerful.

A full listing of the available math functions can be found at:
https://numpy.org/doc/stable/reference/routines.math.html

The math functions in numpy can act on a single number (int or float) or a numpy array of numbers. This makes the numpy functions faster when applied to data science.

### 1.1) Review of Some Math Operations

Below are a few of the math operations introduced in previous tutorials. 

In [80]:
print('The square root of 25 is',np.sqrt(25)) 
print('The number 2 to the 11 power can be found by numpy',np.power(2,11))
print('We can round off a number using numpy: 4.6874 becomes',np.round(4.6874,2))
print('The cosine of pi is', np.cos(np.pi))

The square root of 25 is 5.0
The number 2 to the 11 power can be found by numpy 2048
We can round off a number using numpy: 4.6874 becomes 4.69
The cosine of pi is -1.0


### 1.2) Trig and Angular Conversion Functions


NumPy has the full range of Trigonometric, inverse trig, and Hyperbolic functions.

In general, the functions assume angles in radians, but there are also functions to change between degrees and radians.

See below for some examples.

In [81]:
# Example trig functions
print('Sine of pi/2 = ', np.sin(np.pi/2))
print('The inverse cosine of 0.5 =',np.arccos(0.5))
print('The hyperbolic tangent of pi/2 =',np.tanh(np.pi/2))

Sine of pi/2 =  1.0
The inverse cosine of 0.5 = 1.0471975511965979
The hyperbolic tangent of pi/2 = 0.9171523356672744


In [82]:
#This example shows the numpy function to change degrees to radians
angle_deg = 60
angle_rad = np.deg2rad(angle_deg)
print("an angle of ", angle_deg," degrees is equal to ", angle_rad," radians")

an angle of  60  degrees is equal to  1.0471975511965976  radians


In [83]:
#This example uses several functions together to get the inverse tangent in degrees with the correct quadrant.
x = 3
y = 4
print(np.degrees(np.arctan2(y,x)))
print(np.degrees(np.arctan2(y,-x)))


53.13010235415598
126.86989764584402


In [84]:
angle_rad = 1.3
angle_deg = np.rad2deg(angle_rad)
print("an angle of ", angle_rad," radians is equal to ", angle_deg," degrees")

an angle of  1.3  radians is equal to  74.48451336700703  degrees


### 1.3) Rounding functions

There is a set of numpy functions for various rounding processes with more options than the built-in round function. 

* `np.round(x,d)` rounds off a float to the given decimals and returns it as a float value 


In [34]:
#Various examples
x = 450.598756
print('This is the built-in round function',round(x),type(round(x)))
print('This is the numpy round function',np.round(x,0),type(np.round(x,0)))
print('This is the numpy round function with three digits',np.round(x,3),type(np.round(x,3)))
print('The numpy fix function rounds down',np.fix(x),type(np.fix(x)))
print('The numpy floor function rounds down',np.floor(x),type(np.floor(x)))
print('The numpy ceiling function rounds up',np.ceil(x),type(np.ceil(x)))



This is the built-in round function 451 <class 'int'>
This is the numpy round function 451.0 <class 'numpy.float64'>
This is the numpy round function with three digits 450.599 <class 'numpy.float64'>
The numpy fix function rounds down 450.0 <class 'numpy.float64'>
The numpy floor function rounds down 450.0 <class 'numpy.float64'>
The numpy ceiling function rounds up 451.0 <class 'numpy.float64'>


In [35]:
print("In this example, you can get the decimal part of a floating point number")
x = 450.598756
print(x-np.floor(x))

In this example, you can get the decimal part of a floating point number
0.5987559999999803


### 1.4) Other functions in NumPy

The full range of mathematical functions to operate on single values in numpy is beyond the scope of this tutorial, but I list some of the categories below.

* exponents
* logarithms
* complex numbers
* miscallaneous

In [13]:
import numpy as np

## 2.0) Creating NumPy arrays

NumPy is particularly powerful due to its ability to deal with arrays of data instead of just single values. 

We have explored basic array creation in previous tutorials, but show some additional methods here. 

### 2.1) Manual array creation

As a reminder from previous tutorials, the basic `np.array()` function creates a numpy array.

* 0 D arrays are single values.
* 1 D arrays are a set of values in a row.
    * it has a single index for the position in the row 
* 2 D arrays are a table of values (with rows and columns).
    * it has two indexes the first for the row and the second for the column.
* 3 D arrays are like a cube of data with a table at each layer.
    * it has three indexes, the first for the layer, then the row, then the column.

You can get the number of dimensions using the method `.ndim` on the array.
You can get the shape with the `.shape` method.

Examples of each are shown below.

In [40]:
# 0D arrays


arr = np.array(42)

print('The array is',arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)


The array is 42
It has 0 dimensions.
The shape is ()


In [41]:
# 1D array

arr = np.array((1, 2, 3, 4, 5))
print('The array is',arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)

The array is [1 2 3 4 5]
It has 1 dimensions.
The shape is (5,)


In [42]:
#2D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('The array is',arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)

The array is [[1 2 3]
 [4 5 6]]
It has 2 dimensions.
The shape is (2, 3)


In [48]:
#3D arrays.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6] ,[4, 5, 6]], [[1, 2, 3], [4, 5, 6],[1, 2, 3]]])

print('The array is')
print(arr)
print('It has',arr.ndim,'dimensions.')
print('The shape is', arr.shape)

The array is
[[[1 2 3]
  [4 5 6]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]
It has 3 dimensions.
The shape is (2, 3, 3)


In [68]:
#Higher dimensional arrays.
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### 2.2) Array creation from a list

If you already have data in a list, you can convert the list to an array as long as all items in the list are the same DataType.

In [70]:
list = [3,7,2,6]
print('List is',list,type(list))

array = np.array(list)
print('Array is',array,type(array))

List is [3, 7, 2, 6] <class 'list'>
Array is [3 7 2 6] <class 'numpy.ndarray'>


If the list has multiple DataTypes you can still convert it to an array but all of the values will be converted to the string DataType.

In [73]:
list = [3.0,'7',2,6]
print('List is',list,type(list))

array = np.array(list)
print('Array is',array,type(array))

List is [3.0, '7', 2, 6] <class 'list'>
Array is ['3.0' '7' '2' '6'] <class 'numpy.ndarray'>


If you have multiple lists you can convert them to a 2D array with each list being a row of the 2D array. Note the arrays must have the same length to do this so that the rows have the same number of columns. 


In [78]:
list1 = [3,7,2,6]
list2 = [4,2,8,7]

array = np.array([list1,list2])
print('Array is')
print(array)
print('Array shape is',array.shape)

Array is
[[3 7 2 6]
 [4 2 8 7]]
Array shape is (2, 4)


### 2.3) Special Array Creation

Below are some special ways to create an array and fill the array with specific values or patterns

#### Zero arrays

This creates an array of the specified size with zero values at each location.

In [54]:
# 1 D zeros array
a = np.zeros(5)
print("1D Zeros Array:")
print(a)

1D Zeros Array:
[0. 0. 0. 0. 0.]


In [55]:
#Creating an 2D array of zeros.
zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("2D Zeros Array:")
print(zeros_array)

2D Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


#### Ones arrays

This creates an array with a value of 1 at each location. 

In [77]:
#Creating an array of ones.
ones_array = np.ones((3, 2))  # 3 rows, 2 columns
print("\nOnes Array:")
print(ones_array)


Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Filled arrays

This creates an array with a value you choose at each location. You put in the shape first (as a tuple) and then give the value. 

This fill value can be a number or the `np.nan` (not a number). 


In [58]:
full_array = np.full((3,2),25.)
print(full_array)

[[25. 25.]
 [25. 25.]
 [25. 25.]]


In [57]:
full_array = np.full((3,2),np.nan)
print(full_array)

[[nan nan]
 [nan nan]
 [nan nan]]


#### Ranged arrays

These functions create an array with evenly spaced values.

* `arange` is used for integer values
* `linspace` is used for decimal values

In [79]:
#Ranged arrays
range_array = np.arange(20)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [67]:
lin_array = np.linspace(1,2,5) #start at 1, stop at 2, include 5 values
print(lin_array)

[1.   1.25 1.5  1.75 2.  ]


#### Random arrays

These functions create an array with evenly spaced values.

* `np.random.randint` is used for integer values with a specified low, high, and size
* `np.random.rand` is used for decimal values between zero and 1

In [68]:
#Creating an array with random values.
random_array = np.random.randint(4,8,(2, 3))  # between 4 and 8 with a shape of 2 rows, 3 columns
print("\nRandom Array:")
print(random_array)


Random Array:
[[5 7 5]
 [5 6 4]]


In [59]:
#Creating an array with random values.
random_array = np.random.rand(2, 3)  # 2 rows, 3 columns
print("\nRandom Array:")
print(random_array)


Random Array:
[[0.41872658 0.30324633 0.78732409]
 [0.80916927 0.68959888 0.35457104]]


#### Identity matrix

This is a 2D square array with values of 1 on the diagonal and 0 everywhere else (useful in some linear algebra operations).

In [60]:
ident = np.identity(4)
print(ident)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 3.0) NumPy Array Math

Vectorization concept: 
NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements. This simplifies the code and speeds up the computations.

Examples of these:
- Square all items in array
- Add the same constant to each array


And things you can do with two arrays
(caution on relative size and shapes allowed):
- Add two arrays
- Dot product
- Cross product


### 3.1) Numpy math functions on an array

Here we start by creating a ranged array and then showing the results of different mathematical calculations on the array.

In [85]:
#Setting up the array of numbers
a = np.arange(10)
print('Original array: ', a)

Original array:  [0 1 2 3 4 5 6 7 8 9]


In [86]:
print('Adding a constant',a+2)

Adding a constant [ 2  3  4  5  6  7  8  9 10 11]


In [87]:
print('Multiplying by a constant',a*10)

Multiplying by a constant [ 0 10 20 30 40 50 60 70 80 90]


In [89]:
print('Square of each value:',a**2)

Square of each value: [ 0  1  4  9 16 25 36 49 64 81]


### 3.2) Math with multiple arrays

You can also do element-wise math operations with numpy arrays. 
In this case the first value from the first array is matched with the first value from the second array, and then the math operation is done, returning a new value at that first position. 

As an example, below we create an array with a range of values and a second array over a different range of values. Then we show the element-wise addition, subtraction, multiplication, etc.

In most cases, the arrays must be the same size for these operations to work. 

In [94]:
#Setting up the arrays

a = np.arange(10)  #This array ranges from 0 to 9
b = np.arange(20,40,2) #This array ranges from 20 to 40 in steps of 2
print('array a', a)
print('array b', b)

array a [0 1 2 3 4 5 6 7 8 9]
array b [20 22 24 26 28 30 32 34 36 38]


In [95]:
print("Adding the arrays", a+b)
print("Subtracting the arrays", a-b)

Adding the arrays [20 23 26 29 32 35 38 41 44 47]
Subtracting the arrays [-20 -21 -22 -23 -24 -25 -26 -27 -28 -29]


In [96]:
print("Multiplying the arrays", a*b)

Multiplying the arrays [  0  22  48  78 112 150 192 238 288 342]


In [100]:
#Performing subtraction using arithmetic operator.
temp = a*b
result = (temp+10)/b -5
print("A more complicated math equation")
print(result)

A more complicated math equation
[-4.5        -3.54545455 -2.58333333 -1.61538462 -0.64285714  0.33333333
  1.3125      2.29411765  3.27777778  4.26315789]


In [101]:
#Performing division using numpy functions.
div_ans = np.divide(a, b)
print(div_ans)

[0.         0.04545455 0.08333333 0.11538462 0.14285714 0.16666667
 0.1875     0.20588235 0.22222222 0.23684211]


In [105]:
#Performing division using numpy functions.
div_ans = b/a
print(div_ans)

#Note this one will give a warning since you divided by zero for the first index. The value of inf is the result.

[        inf 22.         12.          8.66666667  7.          6.
  5.33333333  4.85714286  4.5         4.22222222]


/tmp/ipykernel_540878/3970297134.py:2: RuntimeWarning: divide by zero encountered in divide
  div_ans = b/a


In [106]:
#Performing power of two matrices. b to the power of a
pow_ans = np.power(b, a)
print(pow_ans)

[              1              22             576           17576
          614656        24300000      1073741824     52523350144
   2821109907456 165216101262848]


### 3.3) Statistical functions

In [136]:
a = np.arange(10)  #This array ranges from 0 to 9
b = a *10+1        #This array ranges from 1 to 91
c = np.random.rand(10)

print('a\n',a)

print('b\n',b)

print('c\n',c)

a
 [0 1 2 3 4 5 6 7 8 9]
b
 [ 1 11 21 31 41 51 61 71 81 91]
c
 [0.10770127 0.14817633 0.61995691 0.62387043 0.83354071 0.50234868
 0.61236915 0.1616878  0.93213031 0.10898624]


In [137]:
#Getting mean of all numbers in 'a'.
print("mean a:",np.mean(a))
print("mean b:", np.mean(b))
print("mean c:", np.mean(c))


mean a: 4.5
mean b: 46.0
mean c: 0.4650767832654258


In [141]:
#Getting Median of all numbers in 'a'.
print("Median a:",np.median(a))
print("Median b:", np.median(b))
print("Median c:", np.median(c))


Median a: 4.5
Median b: 46.0
Median c: 0.5573589162376533


In [142]:
#Getting sum of all numbers in 'a'.
sum_a = np.sum(a)
print('Sum of values in a:',np.sum(a))
print('Sum of values in b:',np.sum(b))
print('Sum of values in c:',np.sum(c))


Sum of values in a: 45
Sum of values in b: 460
Sum of values in c: 4.650767832654258


In [140]:
#Getting Standard Deviation of all numbers in the arrays
var_b = np.var(b)
print('SD in a:',np.std(a))
print('SD in b:',np.std(b))
print('SD in c:',np.std(c))


SD in a: 2.8722813232690143
SD in b: 28.722813232690143
SD in c: 0.29549630823505696


### 3.4) Matrix math

Numpy has several matrix functions built in.

To illustrate matrix math, we need to have 2D arrays in several shapes. The next cell creates those arrays. 
Some of the code in that cell will be explained later in this tutorial for array manipulation.

* `arr1` 1D array with 3 values
* `arr2` 1D array with 3 values
* `arr3` 1D array with 2 values
* `arr4` 1D array with 2 values
* `arr5` 1D array with 6 values
* `arr6` 2D array with 2 rows and 3 columns
* `arr7` 2D array with  3 rows and 2 columns

In [107]:
arr1 = np.arange(3)
arr2 = arr1 + 3
arr3 = np.arange(2)
arr4 = arr3 + 4
arr5 = np.arange(6) 
arr6 = np.reshape(arr5,(2,3))
arr7 = np.reshape(arr5,(3,2))

In [112]:
print('Matrix 1 \n',arr1)
print('Matrix 2 \n',arr2)
print('Matrix 3 \n',arr3)
print('Matrix 4\n',arr4)
print('Matrix 5\n',arr5)
print('Matrix 6\n',arr6)
print('Matrix 7\n',arr7)


Matrix 1 
 [0 1 2]
Matrix 2 
 [3 4 5]
Matrix 3 
 [0 1]
Matrix 4
 [4 5]
Matrix 5
 [0 1 2 3 4 5]
Matrix 6
 [[0 1 2]
 [3 4 5]]
Matrix 7
 [[0 1]
 [2 3]
 [4 5]]


---
Element-wise multiplication can be done when the two arrays are the same shape. In that case each element mulitplies with the same position in the other array.

In [113]:
print(arr1*arr2)

[ 0  4 10]


In [127]:
print(arr3*arr4)

[0 5]


If the two arrays have the same number of columns, then the multiplication can still work.

In [115]:
print(arr1*arr6)

[[ 0  1  4]
 [ 0  4 10]]


In [143]:
print(arr4*arr7)

[[ 0  5]
 [ 8 15]
 [16 25]]


If the arrays don't have the same number of columns, there will be a ValueError indicating the shape incompatibility.

In [116]:
print(arr1*arr7)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

--- 
Matrix multiplication uses a row vs column set up.

The number of columns in the first array has to map to the number of rows in the second array.

**need to explain more**

In [118]:
print(np.matmul(arr1,arr7))

[10 13]


In [120]:
print(np.matmul(arr3,arr6))

[3 4 5]


In [124]:
print(np.matmul(arr6,arr7))

[[10 13]
 [28 40]]


In [125]:
print(np.matmul(arr7,arr6))

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


---
Dot product multiplication

Need to clarify

Cross multiplication

 Need to clarify

In [122]:
print("Dot product of two 1D arrays")
print(np.dot(arr1, arr2))

Dot prodcut of two 1D arrays
14


In [126]:
print("Cross product of two 1D arrays")
print(np.cross(arr1,arr2))

Cross product of two 1D arrays
[-3  6 -3]


## 4.0) NumPy Array Manipulation

### 4.1)  Reshaping arrays

If you have an array with N items total, then you can reshape it into an form where the total items is still N.

For example:
 * A 1D array with 8 items can be reshaped into
     * A 2D array with 2 rows and 4 columns
     * A 2D array with 4 rows and 2 columns
     * A 2D array with 8 rows and 1 columns 
 * A 2D array with a shape of (3,4) can be reshaped into
     * A 2D array with a shape of (4,3)
     * A 2D array with a shape of (6,2)
     * A 2D array with a shape of (2,6)
     * A 1D array with a length of 12 items

In [152]:
a = np.arange(8)
print ('The original array with 8 items:')
print(a)
print ('\n')

b = a.reshape(4,2)
print ('The modified to 4 rows and 2 columns:')
print(b)
print ('\n')

print ('The modified to 2 rows and 4 columns:')
print(a.reshape(2,4))


The original array with 8 items:
[0 1 2 3 4 5 6 7]


The modified to 4 rows and 2 columns:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


The modified to 2 rows and 4 columns:
[[0 1 2 3]
 [4 5 6 7]]


### 4.2) Flattening arrays

If you have a 2D array and want to turn it into a 1D array, you have several options.

The standard way is the `.flatten method` which creates one long array that starts with the first row, goes through all of the columns, and then gets the next row. 

If you use the `.flatten(order='F')` syntax, it gets the first column, goes through all of the rows and then gets the next column. It is called the `F` order since this was the standard way in fortran. 

In [156]:
import numpy as np 
a = np.arange(8).reshape(2,4) 
print ('The original array:' )
print (a )
print ('\n') 

print ('After applying the flatten function:' ) 
print("The flattened array:")
b = a.flatten()
print(b)

The original array:
[[0 1 2 3]
 [4 5 6 7]]


After applying the flatten function:
The flattened array:
[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [155]:
#Flattening.
a = np.arange(8).reshape(2,4) 

print ('The original array is:') 
print (a )
print ('\n')  
#Default is column-major. 

print ('The flattened array in F-style ordering:') 
a.flatten(order = 'F')

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


The flattened array in F-style ordering:


array([0, 4, 1, 5, 2, 6, 3, 7])

In [144]:
#Raval.
a = np.arange(8).reshape(2,4) 

print ('The original array is:' )
print(a)
print ('\n'  )

print( 'After applying ravel function:' )
print(a.ravel())  
print ('\n') 

print ('Applying ravel function in F-style ordering:') 
a.ravel(order = 'F')

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


After applying ravel function:
[0 1 2 3 4 5 6 7]


Applying ravel function in F-style ordering:


array([0, 4, 1, 5, 2, 6, 3, 7])

### 4.3) Transpose and Other Axes Manipulation

The numpy function `transpose` takes a 2D input array and flips the rows and columns. 

An array with a shape of 2 rows and 3 columns, will become an array with a shape of 3 rows and 2 columns.

But unlike reshape, the values are moved. So the element that was originally in the row 0, column 2 position will now be in the row 2, column 0 position.


In [154]:
a = np.arange(6).reshape(2,3)
print('Original Matrix \n',a)
print('Transposed Matrix \n',np.transpose(a))

Original Matrix 
 [[0 1 2]
 [3 4 5]]
Transposed Matrix 
 [[0 3]
 [1 4]
 [2 5]]


The numpy function `squeeze` will reduce the dimensions of an ND array if one or more of the dimensions have a size of 1. 

In the example below, the x array is a 3D matrix, with one layer, 3 rows,and 1 column.
After squeezing it, we get a 1D array with 3 items. 

This can be useful if you are extracting a subset of data from a larger dimensional data structure. 

In [162]:
x = np.array([[[0], [1], [2]]])
print('Original array \n',x)
print('Original shape',x.shape)

print('\n after the squeeze')
y = np.squeeze(x)
print(y)
print('Shape of new array', y.shape)

Original array 
 [[[0]
  [1]
  [2]]]
Original shape (1, 3, 1)

 after the squeeze
[0 1 2]
Shape of new array (3,)


When working with larger dimensional data sets, there are a variety of functions and methods that can transform the ND array by swapping or rolling axes that go beyond the scope of this tutorial.

### 4.4) Joining arrays

Different ways

In [120]:
#Concatenation.
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  
#Both the arrays are of same dimensions. 

print ('Joining the two arrays along axis 0:' )
print (np.concatenate((a,b)) )
print ('\n')  

print ('Joining the two arrays along axis 1:') 
print( np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [126]:
#Stacking.
a = np.array([[1,2],[3,4]]) 

print ('First Array:') 
print (a )
print ('\n')
b = np.array([[5,6],[7,8]]) 

print ('Second Array:') 
print (b) 
print ('\n')  

print ('Stack the two arrays along axis 0:' )
print (np.stack((a,b),0) )
print ('\n')  

print ('Stack the two arrays along axis 1:') 
print (np.stack((a,b),1))

First Array:
[[1 2]
 [3 4]]


Second Array:
[[5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [128]:
#Splitting arrays.
a = np.arange(9) 

print ('First array:' )
print (a )
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print( b )
print( '\n'  )

print ('Split the array at positions indicated in 1-D array:') 
b = np.split(a,[4,7])
print( b )

First array:
[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [164]:
#Resize array.
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 
print ('\n')

print( 'The shape of first array:' )
print (a.shape )
print ('\n' ) 
b = np.resize(a, (3,2)) 

print ('Second array:' )
print (b) 
print ('\n')  

print ('The shape of second array:') 
print (b.shape )
print ('\n')  
# Observe that first row of a is repeated in b since size is bigger. 

print ('Resize the second array:' )
b = np.resize(a,(3,3)) 
print (b)

First array:
[[1 2 3]
 [4 5 6]]


The shape of first array:
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]


The shape of second array:
(3, 2)


Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [166]:
#Insert.
a = np.array([[1,2],[3,4],[5,6]]) 

print( 'First array:' )
print(a) 
print ('\n')  

print ('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a,3,[11,12]) )
print ('\n')  
print ('Axis parameter passed. The values array is broadcast to match input array.')

print ('Broadcast along axis 0:') 
print(np.insert(a,1,[11],axis = 0) )
print ('\n'  )

print ('Broadcast along axis 1:' )
np.insert(a,1,11,axis = 1)

First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:


array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

## 5.0) Very useful NumPy functions and methods

Ones that look at whole array:
- where()
- sort()
- min()
- max()
- mean()
- count()

- ??unique()


Ones that look at specific elements in the array:
- maximum()

#### Some to check things in arrays  
np.isnan

Functions that deal with nan values.

In [147]:
a = np.arange(10)
>>> a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [151]:
np.where([[True, False], [True, True]])

(array([0, 1, 1], dtype=int64), array([0, 0, 1], dtype=int64))

In [153]:
x, y = np.ogrid[:3, :4]
>>> np.where(x < y, x, 10 + y)

array([[10,  0,  0,  0],
       [10, 11,  1,  1],
       [10, 11, 12,  2]])

In [155]:
a = np.array([[0, 1, 2],
...               [0, 2, 4],
...               [0, 3, 6]])
>>> np.where(a < 4, a, -1) 

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

In [157]:
a = np.array([[1,4],[3,1]])
>>> np.sort(a)     

array([[1, 4],
       [1, 3]])

In [159]:
np.sort(a, axis=None) 

array([1, 1, 3, 4])

In [161]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [163]:
array1 = np.array([10, 12, 14, 11, 5])

#Return the largest element. 
maxValue= np.max(array1)

print(maxValue)

14


In [165]:
array = np.array([[10, 17, 25], 
                  [15, 11, 22]])
                  
#Return the largest element of the flattened array.
maxValue = np.max(array)

print('The largest element in the flattened array: ', maxValue)

#Return the largest element in each column.
maxValue = np.max(array, axis = 0)

print('The largest element in each column (axis 0): ', maxValue)

#Return the largest element in each row.
maxValue = np.max(array, axis = 1)

print('The largest element in each row (axis 1): ', maxValue)

The largest element in the flattened array:  25
The largest element in each column (axis 0):  [15 17 25]
The largest element in each row (axis 1):  [25 22]


In [167]:
array1 = np.array([[10, 17, 25], 
                  [15, 11, 22], 
                  [11, 19, 20]])

#Create an empty array.
array2= np.array([0, 0, 0])

#Pass the 'out' argument to store the result in array2.
np.max(array1, axis = 0, out = array2)

print(array2)

[15 19 25]


In [169]:
rray1 = np.array([[10, 17, 25], 
                   [15, 11, 22]])
print('Dimensions of original array: ', array1.ndim)

maxValue = np.max(array1, axis = 1)

print('\n Without keepdims: \n', maxValue)
print('Dimensions of array: ', maxValue.ndim) 

#Set keepdims to True to retain the dimension of the input array.
maxValue = np.max(array1, axis = 1, keepdims = True)

print('\n With keepdims: \n', maxValue)
print('Dimensions of array: ', maxValue.ndim)

Dimensions of original array:  2

 Without keepdims: 
 [25 22 20]
Dimensions of array:  1

 With keepdims: 
 [[25]
 [22]
 [20]]
Dimensions of array:  2


In [171]:
#Max value > initial, returns max value.
array1 = np.array([[10, 25, 17, 16, 14]])
maxValue = np.max(array1, initial = 6)
print(maxValue)

#Max value < initial, returns initial.
array2 = np.array([[10, 25, 17, 16, 14]])
maxValue = np.max(array2, initial = 26)
print(maxValue)

#In case of an empty array, initial value is returned.
array3 = np.array([])
maxValue = np.max(array3, initial = 5)
print(maxValue)

25
26
5.0


In [173]:
rray1 = np.array([10, 12, 14, 11, 5])

#Return the smallest element. 
minValue= np.min(array1)

print(minValue)

# Output: 5

10


In [175]:
array = np.array([[10, 17, 25], 
                  [15, 11, 22]])
                  
#Return the smallest element of the flattened array.
minValue = np.min(array)

print('The smallest element in the flattened array: ', minValue)

#Return the smallest element in each column.
minValue = np.min(array, axis = 0)

print('The smallest element in each column (axis 0): ', minValue)

#Return the smallest element in each row.
minValue = np.min(array, axis = 1)

print('The smallest element in each row (axis 1): ', minValue)

The smallest element in the flattened array:  10
The smallest element in each column (axis 0):  [10 11 22]
The smallest element in each row (axis 1):  [10 11]


In [177]:
array1 = np.array([[10, 17, 25], 
                   [15, 11, 22], 
                   [11, 19, 20]])

#Create an empty array.
array2= np.array([0, 0, 0])

#Pass the 'out' argument to store the result in array2.
np.min(array1, axis = 0, out = array2)

print(array2)

[10 11 20]


In [179]:
array1 = np.array([[10, 17, 25], 
              	    [15, 11, 22]])

print('Dimensions of original array: ', array1.ndim)

minValue = np.min(array1, axis = 1)

print('\n Without keepdims: \n', minValue)
print('Dimensions of array: ', minValue.ndim) 

#Set keepdims to True to retain the dimension of the input array.
minValue = np.min(array1, axis = 1, keepdims = True)

print('\n With keepdims: \n', minValue)
print('Dimensions of array: ', minValue.ndim)

Dimensions of original array:  2

 Without keepdims: 
 [10 11]
Dimensions of array:  1

 With keepdims: 
 [[10]
 [11]]
Dimensions of array:  2


In [181]:
import numpy as np

#Create an array.
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7])

#Calculate the mean of the array.
avg = np.mean(array1)

print(avg)

# Output: 3.5

3.5


In [77]:
#Create a 3D array.
array1 = np.array([[[1, 2], [3, 4]],                     
                    [[5, 6], [7, 8]]])

#Find the mean of entire array.
mean1 = np.mean(array1)

#Find the mean across axis 0.
mean2 = np.mean(array1, 0)

#Find the mean across axis 0 and 1.
mean3 = np.mean(array1, (0, 1))

print('\nMean of the entire array:', mean1)
print('\nMean across axis 0:\n', mean2)
print('\nMean across axis 0 and 1', mean3)


Mean of the entire array: 4.5

Mean across axis 0:
 [[3. 4.]
 [5. 6.]]

Mean across axis 0 and 1 [4. 5.]


In [183]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#By default int is converted to float.
result1 = np.mean(arr)

#Get integer mean.
result2 = np.mean(arr, dtype = int)

print('Float mean:', result1)
print('Integer mean:', result2)

Float mean: 3.5
Integer mean: 3


In [185]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#Keepdims defaults to False.
result1 = np.mean(arr, axis = 0)

#Set keepdims to True.
result2 = np.mean(arr, axis = 0, keepdims = True)

print('Original Array Dimension:', arr.ndim)
print('Mean without keepdims:', result1, 'Dimensions', result1.ndim)
print('Mean with keepdims:', result2, 'Dimensions', result2.ndim)

Original Array Dimension: 2
Mean without keepdims: [2.5 3.5 4.5] Dimensions 1
Mean with keepdims: [[2.5 3.5 4.5]] Dimensions 2


In [187]:
#2D array.  
arr = ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz'] 
  
print ("arr : ", arr) 
  
print ("Count of 'tt'", np.char.count(arr, 'tt')) 
print ("Count of 'tt'", np.char.count(arr, 'tt', start = 0)) 
print ("Count of 'tt'", np.char.count(arr, 'tt', start = 8)) 

arr :  ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz']
Count of 'tt' [2 2 1 0]
Count of 'tt' [2 2 1 0]
Count of 'tt' [1 2 1 0]


In [189]:
#2D array.  
arr = ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz'] 
  
print ("arr : ", arr) 
  
print ("Count of 'Aa'", np.char.count(arr, 'Aa')) 
print ("Count of 'Aa'", np.char.count(arr, 'Aa', start = 8)) 

arr :  ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz']
Count of 'Aa' [1 1 1 1]
Count of 'Aa' [1 0 0 0]


In [191]:
np.unique([0,1,2,0,2,3,4,3,0,4])
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [193]:
x = np.array([[1, 1], [2,3], [3,4]])
>>> np.unique(x)
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [195]:
x = np.array(['o', 'p', 'y', 't', 'h', 'o', 'p'])
>>> u, indices = np.unique(x, return_index=True)
>>> u
np.array(['h', 'o', 'p', 't', 'y'], 
      dtype='<U1')
>>> indices
np.array([4, 0, 1, 3, 2])
>>> x[indices]
np.array(['h', 'o', 'p', 't', 'y'], 
      dtype='<U1')

array(['h', 'o', 'p', 't', 'y'], dtype='<U1')

In [197]:
x = np.array([0, 1, 2, 5, 2, 6, 5, 2, 3, 1])
>>> u, indices = np.unique(x, return_inverse=True)
>>> u
np.array([0, 1, 2, 3, 5, 6])

array([0, 1, 2, 3, 5, 6])

In [199]:
x = np.array([1,2,5,3,4,2,3,2,5,4])
>>> u, indices = np.unique(x, return_inverse=True)
>>> u
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

# Assignments


Not ready yet.

## Exercise 1)

## Exercise 2)

## Exercise 3)