# Solutions for Tutorial 3: Collection Data Types in Python


This notebook accompanies the Tutorial 3 notebook and shows some possible solutions for the Exercises at the end of the Tutorial

This tutorial was compiled for the PAARE project at South Carolina State University in partnership with Clemson University and the University of the Virgin Islands and funded by NSF.  (NSF grant AST  2319415)

* Original posting:
  * JCash 06-13-2025
* Last modification:
  * JCash 06-24-2025

###  Imports needed

It is always best practice to import the needed packages at the very top of the notebook. As a notebook is developed, you can always add to or take from that cell. 

The cell should always be run before any other cells in the notebook, and right after any changes to the import list are made. 

For this tutorial, we will use NumPy.

In [27]:
import numpy as np

# Assignment



In [28]:
# If you reopen the notebook to continue working on the assignments, you probably will need to rerun the import.
import numpy as np

## Exercise 1)

1) Manually create a list containing the names of the eight major planets. 

2) Use the append method to add the names of at least three dwarf planets to your list. 

In [29]:
# Create a list of the names of the planets.

# Use an append to add the names of at least three dwarf planets.

# Print out the full list at the end.


---
**Possible Solution 1**

This example does all of the steps requested but with little explanation or comments.

In [38]:
# Example Solution 1
# Create a list of the names of the planets.
SS = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

# Use an append to add the names of the dwarf planets.
SS.append('Pluto')
SS.append('Ceres')
SS.append('Eris')
SS.append('Haumea')

# Print out the full list at the end.
print(SS)

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres', 'Eris', 'Haumea']


For append you need to add each item one at a time.

---
**Possible Solution 2**

At a first glance, it looks like this one was able to append all of the extra planets in one step, but a closer examination shows that the four dwarf planets were added as a single item, which was a list of the four. We actually wanted them as individual items.

In [1]:
# Example Solution 2
# Create a list of the names of the planets.
SS = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

# Use an append to add the names of the dwarf planets.
SS.append(['Pluto','Ceres','Eris','Haumea'])
# Print out the full list at the end.
print(SS)

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', ['Pluto', 'Ceres', 'Eris', 'Haumea']]


---
**Possible Solution 3**

As an alternative to append, you can use another built-in function called `extend` which acts the way we want. 

In [2]:
# Example Solution 3
# Create a list of the names of the planets.
SS = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

# Use an append to add the names of the dwarf planets.
SS.extend(['Pluto','Ceres','Eris','Haumea'])
# Print out the full list at the end.
print(SS)

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres', 'Eris', 'Haumea']


## Exercise 2)

1) Use the internet to look up information on the eight major planets in our solar system.
2) Manually create a NumPy Array with the values for the mass of each major planet in units of kg.
3) Manually create a NumPy Array with the values for the radius of each major planet in units of m.
    - (You will want to put in the radius values in scientific notation, not as integers) 
5) Using mathematical operations, create a new NumPy Array that holds the calculated values for the average density of each planet.
6) Create a 2D array with rows for the mass, radius, and density, where each column is for a planet.
7) Use slicing on the 2D array to get all of the values for the inner terrestrial planets.
8) Use slicing on the 2D array to get just the density values for the outer jovian planets.

---
**Possible Solution 1**

This cell does the steps required with minimal documentation.

In [3]:
# Enter your code below.

import numpy as np

Pmass = np.array([3.30e+23,4.87e+24,5.97e+24,6.42e+23,1.89e+27,5.68e+26,8.68e+25,1.02e+26])
Prad = np.array([2.44e+6,6.05e+6,6.38e+6,3.396e+6,7.1492e+7,6.0268e+7,2.55e+7,2.47e+7])

Pvol = 4/3*(np.pi)*(Prad**3)
Pden = Pmass/Pvol

full = np.stack([Pmass,Prad,Pden])

print(full[:,0:4])

print(full[2,4:8])

[[3.30000000e+23 4.87000000e+24 5.97000000e+24 6.42000000e+23]
 [2.44000000e+06 6.05000000e+06 6.38000000e+06 3.39600000e+06]
 [5.42320288e+03 5.25018042e+03 5.48812110e+03 3.91330208e+03]]
[1234.81203825  619.44020162 1249.71382594 1615.92314966]


--- 
**Possible Solution 2**

Let's do this again, but with more clarity on the code and output.

In [31]:
# Possible Solution 2
"""
This assignment worked with data about the planets to calculate the densities.

The data used came from:

We use the following variable names:
Pmass is a list of the mass of each planet in units of kg.
Prad is a list of the radius of each planet in units of meters.
Pvol is a list of the volumes of each planet calculated from the radius, assuming a sphere.
Pden is a list of the average density of each planet in units of kg/m^3.
Ptable is a 2D np array.
"""


import numpy as np

# Step 1: Values come from a NASA website.
print('Values for this assignment were taken from a NASA Website.')
print('https://nssdc.gsfc.gov/planetary/factsheet/')

# Steps 2 and 3: Create arrays for the mass and radius.
Pmass = np.array([3.30e+23,4.87e+24,5.97e+24,6.42e+23,1.89e+27,5.68e+26,8.68e+25,1.02e+26])
Prad = np.array([2.44e+6,6.05e+6,6.38e+6,3.396e+6,7.1492e+7,6.0268e+7,2.55e+7,2.47e+7])


# Step 4: Calculate the density assuming a sphere.
Pvol = 4/3*(np.pi)*(Prad**3)
Pden = Pmass/Pvol


# Step 5: Create a 2D array with mass, radius, and density as rows.
Ptable = np.stack([Pmass,Prad,Pden])
print('The full data is:')
print(Ptable)
print('The shape is:',Ptable.shape)

# Step 6: Use slicing on the 2D array to get the values for the inner terrestrial planets.
print('The terrestrial planets:')
# We want all of the rows, but just the four opening columns, so we need an index from 0 up to 4.
print(Ptable[:,0:4])

# Step 7: Use slicing on the 2D array to get just the density values for the outer jovian planets.
print('The Jovian planets:')
# We want just the density row at row index 2, but just the columns starting with Jupiter in index 4 and going to the end.
print(Ptable[2,4:])

Values for this assignment were taken from a NASA Website.
https://nssdc.gsfc.gov/planetary/factsheet/
The full data is:
[[3.30000000e+23 4.87000000e+24 5.97000000e+24 6.42000000e+23
  1.89000000e+27 5.68000000e+26 8.68000000e+25 1.02000000e+26]
 [2.44000000e+06 6.05000000e+06 6.38000000e+06 3.39600000e+06
  7.14920000e+07 6.02680000e+07 2.55000000e+07 2.47000000e+07]
 [5.42320288e+03 5.25018042e+03 5.48812110e+03 3.91330208e+03
  1.23481204e+03 6.19440202e+02 1.24971383e+03 1.61592315e+03]]
The shape is: (3, 8)
The terrestrial planets:
[[3.30000000e+23 4.87000000e+24 5.97000000e+24 6.42000000e+23]
 [2.44000000e+06 6.05000000e+06 6.38000000e+06 3.39600000e+06]
 [5.42320288e+03 5.25018042e+03 5.48812110e+03 3.91330208e+03]]
The Jovian planets:
[1234.81203825  619.44020162 1249.71382594 1615.92314966]


---
**Possible Solution 3**

In this longer example, the data is entered in such a way as to make it easier to read in the code.

Note that the array declaration spans multiple lines, but there is a comma between each value and the comments
are ignored.

In [32]:
import numpy as np


planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]

# Mass of planets in kilograms.
mass = np.array([
    3.30e23,  # Mercury
    4.87e24,  # Venus
    5.97e24,  # Earth
    6.39e23,  # Mars
    1.898e27, # Jupiter
    5.683e26, # Saturn
    8.681e25, # Uranus
    1.024e26  # Neptune
])

# Radius of planets in meters.
radius = np.array([
    2.44e6,   # Mercury
    6.052e6,  # Venus
    6.371e6,  # Earth
    3.396e6,  # Mars
    6.9911e7, # Jupiter
    5.8232e7, # Saturn
    2.5362e7, # Uranus
    2.4622e7  # Neptune
])

volume = (4/3) * np.pi * radius**3
density = mass / volume


planet_data = np.array([mass, radius, density])


inner_terrestrial = planet_data[:, 0:4]


outer_jovian_density = planet_data[2, 4:8]


print("=== Inner Terrestrial Planets (Mass, Radius, Density) ===")
print(inner_terrestrial)

print("\n=== Outer Jovian Planets (Density Only) ===")
print(outer_jovian_density)


=== Inner Terrestrial Planets (Mass, Radius, Density) ===
[[3.30000000e+23 4.87000000e+24 5.97000000e+24 6.39000000e+23]
 [2.44000000e+06 6.05200000e+06 6.37100000e+06 3.39600000e+06]
 [5.42320288e+03 5.24497707e+03 5.51141237e+03 3.89501562e+03]]

=== Outer Jovian Planets (Density Only) ===
[1326.08406378  687.07465368 1270.37123737 1637.72646239]


## Exercise 3)

In this exercise, you are given a filename as a string. This filename contains information about the data contained in the file (a common practice in data science).

You are told that the file name has three parts separated by underscore characters `_`.

You need to:
- Split the string using the delimiter.
- Save the first part of the filename to a variable called `id` and convert it into an integer value.
- Save the second part of the filename to a variable called `period` and convert it into a float.
- Save the third part of the filename into a string variable called `ftype`.

In [5]:
fname = '450119293_0.522044_lc.dat'

# Put your code below.


---
**Possible Solution 1**

This solution does what the assignment asks for, but has no documentation or output to confirm what is happening.

In [6]:
parts = fname.split(sep='_')
id = int(parts[0])
period = float(parts[1])
ftype = parts[2]

---
**Possible Solution 2**

This solution does what the assignment asks for, and has better documentation.

In [7]:
# Take the filename and do a string split using the separator of an underscore.
# This saves the split string as a list in the variable name "parts".
parts = fname.split(sep='_')

# The ID is stored in index 0 of that list and needs to be converted to an integer.
id = int(parts[0])

# The period is stored in index 1 of that list and needs to be converted to a float.
period = float(parts[1])

# The file type is stored in index 2 of that list and can be left as a string. 
ftype = parts[2]

## Exercise 4)

Create a dictionary representing the stellar characteristics of the Sun.

1) Use the internet to look up the values for the Sun.
2) Think about which values are important for an astronomer.
3) Manually create a dictionary of the values.
4) Use the dictionary values to calculate the average density of the Sun from the radius and mass.



---
**Possible Solution 1**

This solution creates the full dictionary as one step with `key:value` pairs.

It has only a few entries in the dictionary (not all that we would care about, but all that are needed for the density).



In [8]:
# Insert your code here.
sun = {"Mass":1.99e30,"Radius":6.96e8,"Temperature":5772,"Luminosity":382.8e24}
density = sun['Mass']/(4/3*3.14*sun['Radius']**3)
print(density)

1409.7982686961336


---
**Possible Solution 2**

This version creates an empty dictionary and then updates it with the keys and values one at a time.

This makes it easier to read the code, and just add what you want to use.


In [9]:
# Create an empty dictionary.
sun_dict={}

# Update the dictionary with keys and values.
sun_dict['Name'] = 'Sol'
sun_dict['Mass'] = 1.99e30       # In units of kilograms.
sun_dict['Mean_Radius'] = 6.96e8 # In units of meters.
sun_dict['Mean_Density'] = 1408  # In units of kg/m^3.
sun_dict['Surface_Gravity'] = 274.0 # In units of m/s^2.
sun_dict['Luminosity'] = 3.82e26    # In units of J/s.
sun_dict['Spectral_Type'] = 'G2 V'

# Print the whole dictionary.
print('Dictionary for the Sun')
print(sun_dict)
print()

# Calculate the density.
density = sun_dict['Mass']/(4/3*3.14*sun_dict['Mean_Radius']**3)

# Print out the calculation, and also compare it to the value in the dictionary.
print("The calculated density is", density,". The value in the dictionary is",sun_dict['Mean_Density'])

Dictionary for the Sun
{'Name': 'Sol', 'Mass': 1.99e+30, 'Mean_Radius': 696000000.0, 'Mean_Density': 1408, 'Surface_Gravity': 274.0, 'Luminosity': 3.82e+26, 'Spectral_Type': 'G2 V'}

The calculated density is 1409.7982686961336 . The value in the dictionary is 1408
